### ISSUE TITLE
Spielerei: Kuchendiagramm für Knoten-Verbindungsstatus und Senderverbinungsstatus

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#10]
Die aktuelle Statistik ist zahlenbasiert. Es gibt schöne JavaScipt Kuchendiagramme, wie z.B.

![dashboard](https://cloud.githubusercontent.com/assets/16710361/19216121/92f5778e-8db0-11e6-882f-1195fb825e85.png)

Quelle https://github.com/FrissAnalytics/shinyJsTutorials

Vielleicht kann man für die Daten

- [x] Knoten-Verbindungen
- [x] Sender-Verbindungen
- [x] Sender-Arten (Raspager1, C9000 oder SDR-Pager)

solche Diagramme dynamisch erzeugen und im rechten Kasten einbauen?

**Comment by dh3wr** [comment]
Beschriftung einfügen, sowohl bei den Sendern als auch bei den Knoten, bitte
![kuchen](https://cloud.githubusercontent.com/assets/16710361/19341771/33b19da2-912f-11e6-8d5e-f36cd9a2072d.PNG)

**Comment by MarvinMenzerath** [comment]
Da die Diagramme mit Legende relativ viel Platz benötigen: sollen die Text-Statistiken "Sender online", "Sender offline", "Knoten online" und "Knoten offline" entfernt werden?

**Comment by dh3wr** [comment]
Ja die können dann weg. Vielleicht kann man die Legende unter die Kuchendiagramme platzieren?
