### ISSUE TITLE
DX-Meldungen u.s.w über RIG´s

### ISSUE THREAD

**Issue by do1bkt** [DecentralizedAmateurPagingNetwork/Web#100]
Hallo,

ich bin beeindruckt wie schnell euer Netz wägst, aber es ist mal Zeit für etwas negatives!
In den letzten Monaten häufen sich die Aussendungen von DX-meldungen, Wetter, u.s.w , und das aus verschieden Quellen,
was das Netz in der Größe nicht immer verarbeitet bekommt, so das diese Meldungen in den folgen sendeschlitz verschoben werden.

Könnte man die User die diese Meldungen absetzen nicht auf einen Nenner bringen um die Nachrichten auf ein Minimum zu reduzieren?
Wir als Sysop´s der Funkrufsender sind ja gewillt solche Sender für den Amateurfunk  bereitzustellen, aber man sollte auch den Stromverbrauch
solcher Anlagen berücksichtigen.
Es ist ja Konterproduktiv Rubriken für solche Meldungen zu generieren, und dennoch Privat adressierte Meldungen mit gleichem Inhalt mehrfach auszusenden.

Was auch auffällt ist,  das in den Rufzeichen Einträge sind die da eigentlich nichts zu suchen haben, die mich eher an eine Rubrik erinnern!
Bitte versteht mich nicht falsch, aber noch ist es überschaubar, was ist wenn es noch mehr User gibt was ich hoffe, und jeder Arbeitet
nach dem Vorgelebten, dann können neue User nur noch ganz schlecht Anschluss finden, so wie zur Zeit bei DMR( zu viele Änderungen). 

Wie bereits beschrieben, ich bin beeindruckt wie das System arbeitet, und das wie es entstanden ist, ich möchte nicht das es aus beschriebenen gründen
Auseinander bricht!!

73 Bernd
DO1BKT

**Comment by dh3wr** [comment]
Hallo Bernd,

Danke für deinen Kommentar. Auch beim doppelten Lesen ist mir noch nicht klar, worauf du dich genau beziehst.
``Es ist ja Konterproduktiv Rubriken für solche Meldungen zu generieren, und dennoch Privat adressierte Meldungen mit gleichem Inhalt mehrfach auszusenden.''

Meinst du die doppelten Rubriken-Aussendungen einmal im Skyper-Format und einmal mit einer RIC entsprechend https://github.com/DecentralizedAmateurPagingNetwork/Core/issues/87 ? Vielleicht ist hier schon die Antwort?

Das Issue würde auch besser zum Core passen als zum Web-Interface, aber egal.

**Comment by dh3wr** [comment]
Any comment? Alles gut nach der Antwort?
