### ISSUE TITLE
Suchfunktion auf Kartenansicht

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#101]
Wäre super, wenn man auf der Kartenansicht auch nach dem Transmitter-Name suchen könnte. Meist muss ich schauen, so einer ist, und dann alle Popups durchklicken. Evlt. auch in der Transmitter-Übersicht einen "show on map" Button, der dann ein neues Fester aufmacht, und auf den betreffenden Sender zoomt, dennoch die anderen ebenfalls anzeigt.

**Comment by dh3wr** [comment]
Dazu müsste man dann neben dem Stift und dem Papierkorb sich noch ein "Map"-Icon machen oder suchen.

**Comment by MarvinMenzerath** [comment]
efe89411dce15a36722bcdcb894552987a24c914
f7ed0db32ab0681a6a39e5a8ad2aaac0a6bae094

Ein direkter Zoom auf den entsprechenden Marker von der Transmitterübersicht aus ist leider nicht ohne Weiteres möglich.
