### ISSUE TITLE
Button-Beschriftung Hover oder Popup

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#102]
Könnte man eine Button-Beschriftung wie "Edit", "Delete", "Send Email to owner(s)" noch bei den Aktions-Buttons einbauen? Nicht dass sich das nicht selbst erklärt, aber trotzdem schön.

**Comment by MarvinMenzerath** [comment]
Der Hover-Text war an das Icon gebunden (jetzt an den Button).
Chrome hat den Hover-Text wie erwartet angezeigt, Firefox allerdings nicht.
