### ISSUE TITLE
Reload table after delete action

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#103]
Wenn man ein Rufzeichen oder einen User löscht, wird die Tabelle nicht neu geladen. Der gerade gelöschte Eintrag wird weiterhin sichtbar angezeigt.

**Comment by MarvinMenzerath** [comment]
Das Problem kann ich nicht nachstellen, die Tabelle wird sofort neugeladen.
Gibt es eine bestimmte Browser-Konfiguration / Netzverbindung / etc.?

**Comment by dh3wr** [comment]
Hat sich wohl erledigt.
