### ISSUE TITLE
DAPNET-Import: Überprüfung vorhandener Calls

### ISSUE THREAD

**Issue by dk4pa** [DecentralizedAmateurPagingNetwork/Web#104]
Hallo,
seit gestern Abend war kein Login mehr möglich.
Nachdem Philipp mein PW neu gesetzt hatte, stellte sich heraus, dass die hinterlegte Pager ID, Name und E-Mail Adresse geändert waren.
Nach kleinerer Suche passten die Daten zu einem anderen Rufzeichen.
So wurden meine Daten überschrieben. Gibt es bei einem Import eine Überprüfung ob das Call bereits vorhanden ist?
Vy73

**Comment by MarvinMenzerath** [comment]
Es wird geprüft, ob bereits ein User mit dem angegebenen Callsign existiert.
Falls ja, wird hier abgebrochen.
Falls nein, wird der User neu angelegt und sein Callsign inklusive der hinterlegten Pager importiert.

**Comment by dh3wr** [comment]
Hier war eine Verwechslung meinerseits zwischen dk4pa und dk4ap der Grund
