### ISSUE TITLE
Transmitter Group kann nicht in Sender Konfiguration geändert werden

### ISSUE THREAD

**Issue by dd8aka** [DecentralizedAmateurPagingNetwork/Web#105]
Sysops haben keine Möglichkeit, die Transmitter Group selbst festzulegen. Nur der Owner (bzw. Admin) der Transmitter Group kann Sender hinzufügen oder löschen.

Ich finde die Handhabung unpraktikabel, da Sysops selbst entscheiden dürfen sollten, welche Informationen auf seinem Sender verfügbar sind.

**Comment by MarvinMenzerath** [comment]
Das Issue ist im [Core](https://github.com/DecentralizedAmateurPagingNetwork/Core) besser aufgehoben, als hier im Web-Interface.
