### ISSUE TITLE
Add coverage to map

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#107]
Kurze Zusammenfassung des Vorgehens:

- [x] Lade Transmitter-JSON herunter
- [x] Vergleiche mit interner JSON Liste den LastUpdate Timestamp
- [x] Wenn LastUpdate später ist als der letzte gespeicherte Update oder der Sender neu ist, führe Berechnung aus
- [x] Dazu das Berechnungsprogramm teils mit festen Werten, teils mit den Sender-Daten aufrufen und drei PNGs erstellen lassen.
- [x] Einbindung der PNGs in die Leaflet Darstellung der Karte
- [x] Checkbox in Transmitter-Popup für "Show Coverage"
- [x] Die Abdeckung-PNGs sollen auf allen Web-Instanzen vorliegen und von dort aus lokal geladen werden.
- [x] Option für "Show all"
- [x] Möglichkeit des Anzeigens der Coverage pro Zeitschlitz wie bei den Sendern, d.h. wenn man "Show only TX with Timeslot" ausgewählt hat und "Show all coverage", dann sieht man, welche Abdeckung in den einzelnen Timeslots besteht und erkennt Überlappungen auf einfache Art
- [x] Deployment und update der PNGs durch rsync-cronjob von c2com.db0sda.ampr.org (Dazu muss noch ein "Read-Only" User eingerichtet werden. Alternative über HTTP Abruf und Vergleich des lastChanged Timestamp. Was einfacher ist, muss man noch herausfinden.
- [ ] Für den Show-All-Modus eine Zusammensetzung der Einzelkarten mit imagemagick durchführen und entsprechend einbinden. Es können für unterschiedliche Zoom-Stufen unterschiedlich große Bilder generiert werden. Evtl. auch gekachelt für die Zoomstufen 6-10. Dies muss sich noch aus der benötigten Größe der Bilder ergeben. Evtl. hat Leaflet auch eine Begrenzung der Bildgröße?

**Comment by MarvinMenzerath** [comment]
> Je nach Möglichkeit: Option für "Show all", sonst Checkbox in Transmitter-Popup für "Show Coverage"

Ein "Show all" wird insofern schwierig, als dass dabei für jeden Transmitter mindestens 2 Requests gesendet werden und ein neuer ImageLayer angezeigt werden müssen. Je nach Browser / Rechner kann das Probleme machen...
Die aktuelle Lösung zeigt die Coverage-Overlays mit einem Klick auf den Transmitter an und blendet sie mit dem zweiten Klick wieder aus.

> Möglichkeit des Anzeigens der Coverage pro Zeitschlitz wie bei den Sendern, d.h. wenn man "Show only TX with Timeslot" ausgewählt hat und "Show all coverage", dann sieht man, welche Abdeckung in den einzelnen Timeslots besteht und erkennt Überlappungen auf einfache Art

Hier gleiches Problem wie oben. Es ist trotzdem möglich, zuerst eine Suche nach Transmittern mit Timeslot durchzuführen und dann die Coverage-Overlays durch einen Klick auf die jeweiligen Transmitter einzublenden.

**Comment by MarvinMenzerath** [comment]
> Für den Show-All-Modus eine Zusammensetzung der Einzelkarten mit imagemagick durchführen und entsprechend einbinden. [...]

Die momentane Lösung sieht so aus, dass beim Klick auf den entsprechenden Button nicht *alle* Overlays für alle Transmitter geladen werden, sondern nur die Overlays für die zur Zeit sichtbaren Transmitter. Das schließt die bekannten Filterfunktionen mit ein und ist mMn nützlicher.
Dadurch ist es natürlich auch möglich, für wirklich alle Transmitter die Overlays zu laden, was allerdings eine Weile dauert und je nach Browser und System zu Instabilität führen kann.

> Deployment und update der PNGs durch rsync-cronjob von c2com.db0sda.ampr.org [...]

Hier erscheint mir momentan eine Lösung mittels WebDav sinnvoll. Dadurch können die Daten nicht nur via rsync, sondern auch durch den Browser oder den Windows Explorer angezeigt / kopiert werden. Außerdem kann man so auf einen extra User verzichten und benötigt nur einen Apache / nginx auf dem Server.
