### ISSUE TITLE
Responsive Ansicht nicht optimal

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#11]
Auf mobilen Androids ist die Seite nicht schön so sehen. Das Layout überlappt sich teilweise. Vielleicht kann man das noch mit dem Framework optimieren?

**Comment by MarvinMenzerath** [comment]
Leider kann man da generell nicht allzu viel machen.
Seit den letzten Commits (im nächsten Release) ist DataTables angewiesen, alle Tabellen responsive zu gestalten: d.h. kein seitliches scrollen, allerdings werden zu große Spalten abgeschnitten und müssen über ein Plus-Symbol pro Zeile ausgeklappt werden.
Alternativ kann man das seitliche Scrollen beibehalten, wobei das größere Teile des Layouts kaputt macht.

Ich schließe das Issue erstmal und wenn dir größere Probleme auffallen, kannst du es ja wieder öffnen...
