### ISSUE TITLE
Lokale Einstellungen bei git pull akzeptieren

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#111]
Wenn ich auf einer Installation die scr/store/default* Dateien geändert habe, kann ich kein git pull machen, da die Dateien anders sind. Kann man die nach einer manuellen Bearbeitung vom update ausnehmen?

**Comment by dh3wr** [comment]
Ich habe die jetzt mal mit stash behandelt, aber das ist etwas unschön, falls es etwas Eleganteres gibt?

**Comment by phl0** [comment]
Evtl. in die .gitignore aufnehmen?

**Comment by dh3wr** [comment]
Was sagt @MarvinMenzerath

**Comment by MarvinMenzerath** [comment]
Das ist in der Tat etwas nervig.
Vorschlag: die `default*`-Dateien mit einer Endung `.example` versehen (müssen dann vom Nutzer kopiert und angepasst werden) und die Installationsanweisungen erweitern. Dann kann man die angepassten Dateien problemlos mit der `.gitignore` ausschließen...

**Comment by dh3wr** [comment]
ok und einen entsprechenden erklärneden Hinweis ausgeben, wenn jemand npm run build ohne die richtigen Dateien vorherangelegt zu haben macht.

**Comment by MarvinMenzerath** [comment]
Erledigt in 50e12c686b10619db4598ad389788eeb1e73c27b und 2034cfcbbb12ce061f694af7370891918eaeb12d.
