### ISSUE TITLE
Farben beim Sender-Kuchen recht gleich

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#113]
![grafik](https://user-images.githubusercontent.com/16710361/30165545-babf4fce-93e0-11e7-86fd-5a25d43018ff.png)
Da kann man nicht viel erkennen. Kann man die im HSV-Raum etwas weiter verteilen?
https://de.wikipedia.org/wiki/HSV-Farbraum
https://de.wikipedia.org/wiki/HSV-Farbraum#/media/File:HueScale.svg

Vielleicht sogar die 360° gleichmäßig über die Anzahl der Kategorien verteilen?

**Comment by MarvinMenzerath** [comment]
So sieht es jetzt aus:
![image](https://user-images.githubusercontent.com/2064514/30203198-9f5bde68-9481-11e7-8407-94eef55b03c0.png)

**Comment by dh3wr** [comment]
sehr gut
