### ISSUE TITLE
Abdeckungskarten werden mobil nicht angezeigt

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#114]
Auch nach längerem warten nicht. Firefox Browser auf Android.
![screenshot_20170907-153729](https://user-images.githubusercontent.com/16710361/30166217-efca3a92-93e2-11e7-9c75-8486fefc754b.PNG)

**Comment by MarvinMenzerath** [comment]
Bei einem Desktop-Browser das gleiche Ergebnis, die Coveragefiles liegen anscheinend nicht im Verzeichnis...

**Comment by MarvinMenzerath** [comment]
Aus irgendeinem Grund fehlten das `dist/assets/coverage/`-Verzeichnis und der Cronjob zur Aktualisierung der Bilddateien.
Habe den Cronjob wieder angelegt und manuell ausgeführt. Geht wieder.
