### ISSUE TITLE
Enhancement: Verlegung der Scrollfunktion nach oben

### ISSUE THREAD

**Issue by dj7lc** [DecentralizedAmateurPagingNetwork/Web#115]
Beim "umblättern" von Listen im DAPNET Web auf kleineren Bildschirmen springt das Feld permanent rauf und runter, weil die Information in den Zeilen gestaucht und dadurch nach unten länger wird. So muss zum "umblättern" jedes mal wieder das Feld gesucht werden. Ist es möglich, das Feld über die Liste zu verlegen?
![dapnet web scrollfunktion nach oben](https://user-images.githubusercontent.com/25125076/30443901-7e6ea398-9981-11e7-8c1b-70aac57756c4.jpg)

**Comment by MarvinMenzerath** [comment]
Gute Idee, auf schmalen Geräten befindet sich die Seitennavigation jetzt unterhalb der Suche und auf breiten Screens rechts daneben.
