### ISSUE TITLE
No update of Call List

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#116]
Manchmal wird trotz neu laden und klick auf die Rotationspfeile die Calls-Liste nicht richtig neu geladen. Die alten Werte bleiben, auch wenn die Benutzung eines anderen Browsers einen neueren Stand zu Tage bringt. Vielleicht kann man da "No cache" irgendwie erzwingen?

**Comment by MarvinMenzerath** [comment]
Das kann ich so nicht nachstellen.
Kannst du in der Entwicklerkonsole nachschauen, ob der Request gemacht wird, die Antwort korrekt aussieht und ob es eventuell eine Fehlermeldung in der Konsole gibt?

**Comment by dh3wr** [comment]
Ich versuche das nachzustellen. Trat gestern mal sporadisch auf.

**Comment by dh3wr** [comment]
Ist nicht mehr aufgetreten
