### ISSUE TITLE
Spielerei: Piwik Analytik

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#12]
Um ein wenig Statistiken erstellen zu können, natürlich anonym, könnte man Piwki in die Seite einbinden.

**Comment by MarvinMenzerath** [comment]
Damit auch andere Analytik-Dienste oder benutzerdefinierte Skripts ausgeführt werden können, würde ich vorschlagen, eine eigene JS-Datei (z.B. `custom.js`) anzulegen.
Diese ist standardmäßig leer, wird aber beim Start der Oberfläche geladen. Dort können dann vom Benutzer Piwik-Skripte o.ä. eingefügt werden.
