### ISSUE TITLE
Unmet dep v2.1.3

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#120]
Was sagt mir das nach ``npm install``
````
├── vue2-leaflet@0.0.55
├── UNMET PEER DEPENDENCY vuex@3.0.0
├─┬ webpack@3.8.1
│ ├─┬ ajv@5.3.0
````

**Comment by MarvinMenzerath** [comment]
Das wird daran liegen, dass `vuex-persistedstate` noch nicht die Peer-Dependency auf `vuex` >= v3.0.0 aktualisiert hat.
Solange es allerdings keine Fehler beim Build gibt (wovon ich noch keine gesehen habe), kann das ignoriert werden.

**Comment by dh3wr** [comment]
Gibt keinen Fehler, dann ist ja alles gut.
