### ISSUE TITLE
Erklärungstexte zu Seiten der Webseite

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#124]
Ich verfasse mal ein paar "Information" Texte zu den Hauptseiten der Weboberfläche, da es nicht allen Usern klar ist. Vielleicht wie bei den Sendereigenschaften als InfoBox rechts?

Calls:
Calls are personal paging transmission to individual receivers.

Subscribers:
A subscriber is logical connection between a name (the callsign) and one or multiple RIC numbers, for example a Skyper address.

News:
The content displayed here are NOT general news about DAPNET, but the recently sent content to rubrics. Every time a user updates the 10 avaiable rubric messages slots, this change will be displayed here.

Rubrics:
On Skyper receivers, there is a feature called rubrics implemented. These are new feeds that the user can select and receive, for example the DX cluster news. Rubrics have to be assigned to a transmitter group, which will send out the rubric name and its content. There are rubric number 1 to 99 possible. The same rubric number can be assigned to different transmitter groups, but take care that the the coverage area of the transmitter groups do no overlap. Hint: Have a look in the map.

All Transmitters:
(Ich mache nach dem Essen weiter)

**Comment by MarvinMenzerath** [comment]
Ich habe die Texte aus dem Issue eingepflegt. Hast du noch weitere Texte?

**Comment by dh3wr** [comment]
All Transmitters:
This overview shows all registered transmitters of the DAPNET network. Before you can connect your transmitter to one of the DAPNET-Nodes, it has to be registered by one of the admins. There are two classes of transmitters: Widerange (>= 1 Watt) and Personal (< 1 Watt). Why is there such a big number of offline transmitters? These are transmitters which have been registered in the past, but apparently are not online now. There is no information store which transmitters "should" be online and which not.
Transmitters have one of multiple owners who can change the settings by themselves. Each transmitters is assigned to one or max. 16 timeslots. This is necessary as they transmit all on the same frequency, but not overlapping at the same time. Be aware to assign no timeslots to your transmitter that are already used in you coverage area. Contact one of the admins, if you need help.

Nodes:
Nodes are the instances of the DAPNET cluster. This list shows the status of them. Due to the "not so good" long range connectivity of the HAMNET, cluster nodes come and go from time to time. This is very unsatisfying, we are working on a solution.

Transmitter Groups:
A transmitter groups is a logical association of one or multiple transmitters to a group. This is necessary to devide the transmitters into regional areas, as not all content has to be transmitted on the whole network. Both personal calls as well als rubric's content have to be linked to a transmitter group. Only transmitters that are member of this group will get the information from the DAPNET node in order to transmit it.

Users:
This is an overview of all registered user account on the DAPNET network. If you are not an admin, you don't see other user's details. You can edit your user by yourself, e.g. change your passwort or your email address.

**Comment by MarvinMenzerath** [comment]
Sind eingepflegt
