### ISSUE TITLE
Umbenennung von "Callsigns" zu "Subscribers"

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#126]
Da auch der Login-Name im Amateurfunk-Gebrauch ein "Callsign" ist, bitte den Menüpunkt und alles was dazu gehört in "Subscribers" umbenennen. Ob wir die API auch ändern sollten, weiß ich noch nicht. Was meint @Taronyu ?

**Comment by Taronyu** [comment]
API-Änderungen haben halt immer größere Auswirkungen, da kann man schnell was übersehen bzw. nicht alles liegt vielleicht unter unserer Kontrolle. Weiß ja nicht, wer die API sonst noch so nutzt.

**Comment by dh3wr** [comment]
Ich würde auch die API so lassen und nur die Anzeige im WEB ändern. Also nur die Stings da.

**Comment by dh3wr** [comment]
Ich habe das mal zumindest in der Anzeige umgebaut.

**Comment by MarvinMenzerath** [comment]
In der API und im Web-Frontend intern würde ich das momentan auch nicht umbenennen wollen. Die Strings zur Anzeige hast du alle erwischt so wie es aussieht.
