### ISSUE TITLE
Add real News to Web-Interface

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#129]
Es gibt die Anfrage, ob man auch wirkliche DAPNET-"News" bereitstellen kann.
Solange https://github.com/DecentralizedAmateurPagingNetwork/Core/issues/2 von @Taronyu noch bearbeitet wird, vielleicht folgenden Workaround implementieren:

Auf ``db0sda.ampr.org`` gibt es einen User ``'dapnet'@'44.%'`` mit einem Schema ``dapnet`` und einer Tabelle ``newsfeed``.
Klassischer Eintrag:
``INSERT INTO `dapnet`.`newsfeed` (`sender`, `category`, `title`, `content`, `link`, `creationdate`, `approved`) VALUES ('dh3wr', 'Web', 'Testeintrag', 'Hier ist schon Tolles zu sehen', 'https://web.update.org', NOW(), '1');``

- [ ] Könnte man eine Sektion mit Titel ''News'' machen, die nach ``creationdate`` absteigend sortiert die Inhalte in einer Tabellen-Ansicht ausgibt?
- [ ]  ''sender'' ist der aktuelle Benutzername aus der http-Session.
- [ ] Ebenfalls eine Möglichkeit, neue "News" zu erzeugen und wenn man selbst der ''sender'' ist, die auch zu löschen oder zu bearbeiten. Wenn man admin ist, dann soll man alle News bearbeiten oder löschen können.
- [ ] Den Inhalt der Spalte ``link`` als html-Link erzeugen mit öffnen im neuen Tab.
- [ ] Das Passwort für den User 'dapnet'@'44.%' kommt per Email.

Alle DAPNET-Web Instanzen fragen db0sda.ampr.org ab; es gibt hier keine Verteilung im Node-Cluster
- [ ] Optional: Bereitstellen eines RSS-Feeds mit den letzten 10 Einträgen.
- [ ] Vielleicht auch die letzten 3 Meldungen auf der Start-Seite darstellen
- [ ] Konfiguration des mysql-Servers und der Login-Daten über eine Datei in src/store

**Comment by dh3wr** [comment]
Man könnte auch aus dem dapnet dokuwiki einen rss feed einbinden. Wäre vielleicht flexibler. Ich finde das mal heraus ob und wie das geht.

**Comment by dh3wr** [comment]
Ich habe jetzt einen RSS Feed, den mal vielleicht auch in der defaulturls Datei konfigurierbar macht.
http://dapnet.db0sda.ampr.org/dokuwiki/feed.php?ns=blog&content=html
oder aus dem Internet
https://hampager.de/dokuwiki/feed.php?ns=blog&content=html

Könnte man dazu einen Newsfeed auf der Startseite irgendwo hinquetschen? Vielleicht nur Überschriften?

**Comment by dh3wr** [comment]
Hier noch ein paar Dings zu den Parametern von feed.php
https://www.dokuwiki.org/tips:blogging#feed_setup

**Comment by MarvinMenzerath** [comment]
Kleines Hindernis: der Webserver schickt keinen entsprechenden CORS-Header raus, sodass ich den Feed nicht abfragen kann:
```
Failed to load https://hampager.de/dokuwiki/feed.php?ns=blog: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8081' is therefore not allowed access.
```

Kannst du dafür sorgen, dass (zumindest bei der `feed.php`) auch ein Header mit `Access-Control-Allow-Origin: *` gesendet wird?

**Comment by dh3wr** [comment]
Sehr schön @MarvinMenzerath . Kann die Schriftgröße noch einen Tick kleiner?
