### ISSUE TITLE
Fehlermeldung "Please fill out all fields" ist irreführend

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#130]
In Verbindung mit #109 bekommt man bei einer "falschen" Verwendung von Punkt oder Komma die Meldung, dass man nicht alle Felder ausgefüllt hat.

**Comment by dh3wr** [comment]
Aufgetreten bei den Sender-Einstellungen

**Comment by MarvinMenzerath** [comment]
Da die Fehlermeldung auf die gleiche Ursache wie bei #109 schließen lässt, mache ich hier zu. Falls der Fehler nach #109 wieder auftritt, einfach nochmal öffnen.
