### ISSUE TITLE
New support Email Address

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#132]
Bitte ``rwth-afu at online.de`` durch ``support at hampager.de`` ersetzen in allen Dokumenten. Wir haben jetzt ein osTicket-System, um loadbalancing der Anfragen durchführen zu können.

**Comment by MarvinMenzerath** [comment]
https://github.com/DecentralizedAmateurPagingNetwork/Web/commit/797889ab3034a097c9c6d2dbb88cf39ae96351cf
