### ISSUE TITLE
Display Transmitter Version in Transmitter List

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#138]
Hinter den Transmitter Software Namen bitte die Version anzeigen. In der Vue zum Edit Transmitter ist das schon drin.

Vielen Dank

**Comment by MarvinMenzerath** [comment]
Ist drin, sorgt allerdings für viele Zeilenumbrüche innerhalb der Tabelle. Gibt es Infos, die stattdessen aus der Übersicht entfernt werden und nur in der Detail-Ansicht angezeigt werden sollen?

**Comment by dh3wr** [comment]
Connected since kann auf die Form DD.MM.YY hh:mm gebracht werden. Dann spart man 5 Zeichen.
Owner könnte auch so gemacht werden, dass ein ggf. vorhanderer 2. bis n. Owner auf jeden Fall eine neue Zeile bekommt.

**Comment by MarvinMenzerath** [comment]
Mit der Änderung des Zeitformats und einer generellen Verbreiterung der Seite (auf entsprechenden Endgeräten) ist die Darstellung jetzt wieder korrekt.
