### ISSUE TITLE
Zanata translation framework

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#142]
@MarvinMenzerath Mit der Web-Variante geht es zumindest out-of-the-box nicht.
![grafik](https://user-images.githubusercontent.com/16710361/36895440-2e3ff1f2-1e0f-11e8-82b1-90383fb8e312.png)

Es gibt mehrere Hinweise auf http://okapiframework.org/wiki/index.php?title=JSON_Filter, aber keine Ahnung, wo man diesen Filter aktiveren soll.

**Comment by dh3wr** [comment]
Der hier angegeben Link geht nicht: http://docs.zanata.org/en/release/user-guide/documents/raw-documents/#supported-formats
![grafik](https://user-images.githubusercontent.com/16710361/36895487-58463808-1e0f-11e8-92e0-2a71791a30f7.png)

**Comment by dh3wr** [comment]
Mehr dazu: https://zanata.atlassian.net/browse/ZNTA-667

**Comment by dh3wr** [comment]
Erstmal low prio, scheint nicht so einfach zu sein

**Comment by MarvinMenzerath** [comment]
Es scheint auch nur sehr wenige Alternativen zu geben und noch weniger, die ihre Services kostenfrei zur Verfügung stellen...

**Comment by MarvinMenzerath** [comment]
Ich habe gerade ein Projekt bei https://poeditor.com eingerichtet. Dort können die Strings relativ einfach übersetzt werden und Freiwillige können Übersetzungen beisteuern.
Momentan importiere ich Englisch, Deutsch und Spanisch und richte einen Sync mit dem GitHub-Repository (falls möglich) ein.
