### ISSUE TITLE
Welcome Page improvement

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#143]
Um die Startseite für Unbedarfte etwas deskriptiver zu gestalten, habe ich an ein Karusell gedacht. Z.B. https://ssense.github.io/vue-carousel/

Wie auf der IHF-Homepage wäre ein i18n verwalteter String für Title und Subtitle cool. Die Bildgröße würde auch wie beim IHF auf 400x400 festlegen.

Könnte man zum einfachen Austauschen ein directory machen, von dem dynamisch alle Bilder genommen werden? Dann muss natürlich die i18n Zuordnung passen. Oder man macht die i18n Stuktur so
```
"carusell": {
  "content1": {
    "title": "bla",
    "subtitle: "bla",
    "filename: "meincoolesbild.jpg"
  },
  "content2": {
    "title": "bla",
    "subtitle: "bla",
    "filename: "meinnochcooleresbild.jpg"
  }
}
```
Der Algorithmus würde dann für jedes Bild im dem Verzeichnis den Filenamen vergleichen mit dem i18n-File und wenn es ihn gibt, dann entsprechend das Bild samt Text darstellen.

Ist dazu aufwendig? Sonst beschänken wir uns auf Bild1 bis Bild6 mit festem Filename und fertig.

(Unschön natürlich im i18n-File Dateinamen zu haben)

**Comment by dh3wr** [comment]
Das impliziert auch ein bischen Aufräumen auf der Startseite. Dazu mal mündlich ein paar Ideen.

**Comment by MarvinMenzerath** [comment]
So ein Element kann ich einbauen, ob das aber so einfach über die i18n-Strings verwaltet werden kann, muss ich ausprobieren...

**Comment by MarvinMenzerath** [comment]
Die von dir vorgeschlagene Bibliothek funktioniert folgendermaßen:
In der `Home.vue`-Datei wird im `<template>`-Bereich das `<carousel>` angelegt, welches beliebig viele `<slide>`-Elemente beinhalten kann. Hier können auch die i18n-Funktionen verwendet werden.

Beispiel:
```html
<carousel>
	<slide>
		<h1>{{ $t('home.welcome.title') }}</h1>
		<p v-html="$t('home.welcome.text')"></p>
	</slide>
	<slide>
		<img src="~@/assets/img/afu-dapnet-logo.png" alt="DAPNET Logo"/>
	</slide>
</carousel>
```

Angeblich können beliebige Elemente in diesen Slides verwendet werden (z.B. eine Karte, Statistiken, Diagramme, etc.). Ich pushe gleich einen ersten Test, der den bekannten Home-Text und das DAPNET-Logo beinhaltet und alle 5s das angezeigte Element wechselt.

**Comment by dh3wr** [comment]
Super. Man könnte man schauen, ob man tatsächlich die OSM-Karte dynamisch in die Show einbinden kann. Vielleicht dann noch zusätzlich einen Link für die Kartenansicht im Full-Screen, so wie hier:
http://hamnetdb.net/
![grafik](https://user-images.githubusercontent.com/16710361/36983742-72a1cd08-2093-11e8-817c-8c6d60b71a43.png)

**Comment by MarvinMenzerath** [comment]
Ich habe die 9 Bilder mit einem Dummy-Text (siehe i18n Dateien) eingepflegt.

**Comment by dh3wr** [comment]
Vielleicht noch die Pfeile am linken und rechten Rand aktivieren?
Und Höhe 400 px?

**Comment by MarvinMenzerath** [comment]
> Vielleicht noch die Pfeile am linken und rechten Rand aktivieren?

Aktiviert.

> Und Höhe 400 px?

Die Bibliothek orientiert sich am größten Element in den Slides. Ich kann die Größe von 400px erzwingen, allerdings werden dabei die Bilder auch nach 400px abgeschnitten...

**Comment by dh3wr** [comment]
Habe nur 400x400 px Bilder dir geschickt

**Comment by MarvinMenzerath** [comment]
Öhm, dann läuft hier was anderes schief. Ich schau nochmal danach...

**Comment by dh3wr** [comment]
Die Texte außer von Bild1 kommen auch noch nicht..

**Comment by MarvinMenzerath** [comment]
So, jetzt sollte es besser aussehen.
Die Texte gehen bei mir alle...

**Comment by dh3wr** [comment]
@MarvinMenzerath Ich hatte "German" eingestellt...

**Comment by dh3wr** [comment]
Auf der mobilen Ansicht werden bei manchen Bildern die vorherigen links am Rand noch dargestellt und insg. ist das Carousel sehr hoch.
![screenshot_20180305-172913](https://user-images.githubusercontent.com/16710361/36987081-cf07793c-209b-11e8-85ca-2af6dce83f67.png)
![screenshot_20180305-173002](https://user-images.githubusercontent.com/16710361/36987086-d1aef4ee-209b-11e8-9449-79ed34b63d93.png)
![screenshot_20180305-173009](https://user-images.githubusercontent.com/16710361/36987094-d3d06352-209b-11e8-83bf-712985c5d0ac.png)

**Comment by dh3wr** [comment]
- [ ] Text bitte vertikal zentrieren
- [ ] Soll die Hintergrundfarbe der Fotos an das leichte Grau der DAPNET-Oberfläche angepasst werden? Oder lieber transparent als PNG?

**Comment by dh3wr** [comment]
Super mit den Links. Kann man da noch target blank rein machen? Im i18n oder im vue?
PNGs mache ich in transparent

**Comment by MarvinMenzerath** [comment]
> Kann man da noch target blank rein machen?

Ist drin

---
> Im i18n oder im vue?

In den i18n-Dateien gibt es zu jedem Karussell-Eintrag neben `title` und `text` auch einen `link`. Da muss die URL rein.

**Comment by dh3wr** [comment]
Ich meinte das ''target=''. Die Links sind schon drin. Hat sich also erledigt.
