### ISSUE TITLE
Make Map available without login

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#144]
Sie auch #143 würde ich gerne auf der Startseite bereits die Karte präsentieren oder zumindest einen Link dazu, auch ohne Anmeldung. Kann man das irgendwie machen, ohne die map.vue zu duplizieren? Da ist natürlich auch eine Link in dem Popup auf den Transmitter-Edit drin, der sollte dann nicht aktiv sein. Die API ist bereits so, dass man für den call /transmitter keinen Auth braucht.

Idee ist, dass sich Interessierte schon mal ohne Anmeldung die Sender und ihre Abdeckung anschauen können.

**Comment by MarvinMenzerath** [comment]
Am einfachsten wäre es, einfach auf die Karte zu verlinken und diesen Aufruf auch unangemeldet zu erlauben. Allerdings sind die Nodes nicht ohne Anmeldung bei der API verfügbar.
Da wäre es sinnvoller, eine "light" Version der Karte auf der Startseite anzubieten, die wirklich nur die Transmitter anzeigen kann und sonst nichts...

**Comment by dh3wr** [comment]
Letzteres bitte :-)

**Comment by MarvinMenzerath** [comment]
Eine Platzierung im Karussell funktioniert übrigens nicht. Die Karte wird nicht vollständig geladen und die Karte selbst lässt sich nicht verschieben, ohne den ganzen Slider zu verschieben.

**Comment by dh3wr** [comment]
Ok, dann kommt im Karusell nur ein Bild. Reicht auch. Über die Position ist noch zu verhandeln, vielleicht tauschen wir das mit der Statistik oder so.

Noch was: Die Abdeckungskarten gehen in dieser Ansicht nicht. Kann man die hinzufügen?
Ebenfalls wäre bei Klick auf die Karte (oder sonst als Link) eine Fullscreen Ansicht der Karte in einem neuen Fenster ohne Nav-Bar wünschenswert. Wie auf hamnetdb.net, wenn man auf die Karte links klickt.

**Comment by MarvinMenzerath** [comment]
> Die Abdeckungskarten gehen in dieser Ansicht nicht. Kann man die hinzufügen?

Kann man. Die hatte ich absichtlich raus gelassen, weil die Darstellung so klein war.

---
> Ebenfalls wäre bei Klick auf die Karte (oder sonst als Link) eine Fullscreen Ansicht der Karte in einem neuen Fenster ohne Nav-Bar wünschenswert.

Fullscreen wäre komplett am Vue.js Framework vorbei. Auf der Home-Seite kann ich einfach einen Link zur "normalen" Kartenansicht unter die Karte setzen, aber tatsächlicher Fullscreen geht erstmal nicht ohne Weiteres.

**Comment by dh3wr** [comment]
kann ja eine Vue.js Seite sein, in der nichts als die Karte ist, oder?

**Comment by dh3wr** [comment]
Ungemeldet tut sich nichts beim Link

**Comment by MarvinMenzerath** [comment]
Für die Karte habe ich eine deutlich schönere Lösung durch ein Fullscreen-Plugin gefunden. Durch den neuen Button unter dem Zoom kann der Browser die Karte auf dem ganzen Bildschirm anzeigen.

Den Link auf der Home-Seite zeige ich ab sofort nur noch angemeldeten Benutzern an. Nutzern ohne Login fehlen die Berechtigungen zum Abruf der Nodes, sodass die Seite sowieso nicht erfolgreich geladen werden kann.

**Comment by dh3wr** [comment]
Könnte man das Fullscreen-Plugin auch auf der Startseite einbauen?

**Comment by MarvinMenzerath** [comment]
Ist drin
