### ISSUE TITLE
Language Switcher in Menu-Bar

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#147]
In der Menu-Bar ist zwischen Users und dem Login-Namen ja noch Platz. Könnte man da ein Pull-Down Menu machen mit der Sprachauswahl? Würde mehr ins Auge fallen als unten auf der Seite. Evtl. sogar mit passenden Länderflaggen? Könnte man schon mal für en, dl, es, pl, fr und thailand vorbereiten....

**Comment by dh3wr** [comment]
Beispiel: https://icons8.de/icon/15502/deutschland

Ebenfalls für das Pull-Down menu von der Funktion her
![grafik](https://user-images.githubusercontent.com/16710361/37039223-3605ab2a-2157-11e8-8bcc-cf3c1563ff54.png)
https://icons8.de

**Comment by MarvinMenzerath** [comment]
![image](https://user-images.githubusercontent.com/2064514/37039750-7f346128-2158-11e8-8bd3-98a1cdd8ef9e.png)

**Comment by dh3wr** [comment]
Sehr gut. Können wir die aktuelle Sprache noch per Icon im Titel des Pulldown anzeigen?
