### ISSUE TITLE
Mit https wird fontawesome-webfont nicht geladen

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#150]
![grafik](https://user-images.githubusercontent.com/16710361/38330334-9751f34c-3850-11e8-8aad-c3beedf46d65.png)

Vielleicht lokal hosten?

**Comment by MarvinMenzerath** [comment]
FontAwesome wird lokal gehostet. Diese Domain `rough-chillbar.net` wird auch nicht im gesamten Projekt verwendet, wo kommt die her?
Der Grund für diesen Block ist: hampager.de wird via HTTPS geladen, die Schriftdatei soll allerdings via HTTP von `rough-chillbar.net:1337` geladen werden.
Daher sieht das für mich nach einem Problem mit dem lokalen Setup aus...

**Comment by dh3wr** [comment]
ok, wenn ich die Seite aufmache, werden noch andere URLs, die ich in anderen Tabs auf habe, in der Inspektor-Ansicht als Fehler angezeigt. Löschen des Caches hat das Problem behoben. Verstehen tue ich es nicht, vielleicht eher ein FF Problem.
