### ISSUE TITLE
On new Transmitter input form, check if already existing

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#153]
Wenn man das Formular für einen neuen Sender aufruft, ausfüllt und abschickt, möge überprüft werden, ob es einen Sender mit dieser Bezeichnung schon gibt. Wenn ja, dann soll das Anlegen (was die alten Einstellungen überschreibt) unterbunden werden.

**Comment by phl0** [comment]
Heute 2x live getestet und bestätigt :-(
