### ISSUE TITLE
Remove white-Space characters from input fields

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#154]
Es kommt durch C&P schon mal vor, dass bei Eingaben am Ende noch ein \n oder \r\n vorhanden ist. Der Core nimmt das dann nicht an, allerdings ist die Fehlermeldung: ``Unhandled HTTP error 406``
Das ist nicht so aussagenkräftig.

Um das zu vermeiden, könnte man vor der Erstellung der JSON Anfrage white-spaces entfernen?

**Comment by MarvinMenzerath** [comment]
Mit https://github.com/DecentralizedAmateurPagingNetwork/Web/commit/d38cb724540ce158c448693fc127f22e4ab27c72 werden nun das JSON-Objekt und die URL vor dem Versand an den Server getrimmt.
Das sollte keine Probleme machen, trotzdem in der nächsten Zeit ein Auge drauf werfen, ob nicht dennoch relevante Inhalte getrimmt werden.

Außerdem sollte mMn ein solches Trimming auch beim Server stattfinden, da ja nicht nur das Web-Interface Requests mit Leerzeichen abschicken kann...
