### ISSUE TITLE
Reminder englischer Text 

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#155]
https://twitter.com/dc7ia/status/984107131694649344?s=09

**Comment by dh3wr** [comment]
In poeditor ist der Englische Text geändert. Wir das nun auch automatisch ins github übernommen?
@MarvinMenzerath

**Comment by dh3wr** [comment]
Bitte finische Version auch ins Sprachenmenü einbauen, danke. @MarvinMenzerath

**Comment by MarvinMenzerath** [comment]
> In poeditor ist der englische Text geändert. Wird das nun auch automatisch ins github übernommen?

Nicht automatisch, das muss vorher exportiert werden. Entweder über die Export-Funktion in meinem Account oder manuell über POEditor die JSON-Datei herunterladen und ins Repository kopieren.

---
> Bitte schwedische Version auch ins Sprachenmenü einbauen, danke.

Ist schon eingebaut: https://github.com/DecentralizedAmateurPagingNetwork/Web/commit/0162c9668c42065734cdd98221658013f289d0a4
