### ISSUE TITLE
Minor: Add location picker

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#158]
Für die Punkte, wo locations angegeben werden müssen (also Sender und Nodes), könnte man noch einen Location Picker einbauen.

Z.B. http://labs.easyblog.it/maps/leaflet-locationpicker/

In ``http://labs.easyblog.it/maps/leaflet-locationpicker/src/leaflet-locationpicker.js`` gibt es auch die Parameter. die man setzen kann. Da wäre zum einen die osm URL aus der globalen Config einzubauen und die Größe noch etwas anzupassen. Es gibt auch eine Beispiel, das Länge und Breite einzeln ausgibt.
Nur mal so 'ne Idee..

````
var baseClassName = 'leaflet-locpicker',
			baseLayers = {
				'OSM': http + '//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
				'SAT': http + '//otile1.mqcdn.com/tiles/1.0.0/sat/{z}/{x}/{y}.png'
				//TODO add more free base layers
			};

		var optsMap = {
				zoom: 0,
				center: L.latLng([40,0]),
				zoomControl: false,
				attributionControl: false
			};

		if($.isPlainObject(opts) && $.isPlainObject(opts.map))
			optsMap = $.extend(optsMap, opts.map);

		var defaults = {
			className: baseClassName,
			location: optsMap.center,
			locationFormat: '{lat}{sep}{lng}',
			locationMarker: true,
			locationDigits: 6,
			locationSep: ',',
			activeOnMove: false,
			position: 'topright',
			layer: 'OSM',
			height: 140,
			width: 200,
			cursorSize: '30px',
			map: optsMap,
			onChangeLocation: $.noop
````

**Comment by dh3wr** [comment]
Kann man die Karte noch auf die eingetragene Location zentrieren, bitte?

**Comment by dh3wr** [comment]
Kann man noch die Beschriftung "Location Picker" in das Übersetzungsframework aufnehmen, bitte?

**Comment by MarvinMenzerath** [comment]
Ist da schon drin:
![image](https://user-images.githubusercontent.com/2064514/40967959-b50c1f86-68b4-11e8-8479-35c083f318cf.png)
