### ISSUE TITLE
Tabellen-Seiten-Umschaltung mit Umbruch auf 24" Screen

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#159]
Im Dev branch 2a434b0d07940bd071c5bdc9e503ffe6d730d3f2

![grafik](https://user-images.githubusercontent.com/16710361/38807465-f7f9082c-417c-11e8-815e-294ce51fa524.png)

**Comment by MarvinMenzerath** [comment]
Firefox hat seine `input`-Elemente wohl gerne etwas breiter, habe die ganze Spalte etwas verbreitert.
