### ISSUE TITLE
Passwort-Generator mit nicht-verwechselbaren Zeichen

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#162]
Zur Zeit werden I und L in Groß und Kleinschreibung sowie 0 und O verwednet. Um weniger Support-Tickets, die sich um eine Verwechslung dieser Zeichen drehen, bearbeiten zu müssen, könnte man vielleicht den Zeichenvorat zu beschränken, dass keine je nach Schriftart nicht unterscheidbaren Zeichen enthalten sind.
Beispiel: https://www.trinler.net/service/tools/pwgen/

**Comment by MarvinMenzerath** [comment]
Als ersten Schritt habe ich die Schriftart im Eingabefeld angepasst, damit die Unterschiede besser sichtbar sind:
![image](https://user-images.githubusercontent.com/2064514/39563139-42eb5314-4eaf-11e8-9c58-441ff1ececc6.png)

Ein paar Zeichen auszuschließen ist zwar machbar, klingt aber nach der falschen Lösung.

**Comment by dh3wr** [comment]
Och, auch wenn das Ergebniss nicht maximale Entropie hat könnte man mit dem Ausschluss leben, finde ich. Es wird ja keiner einen Entropie-Attack machen in diesem Rahmen hier.

**Comment by MarvinMenzerath** [comment]
OK, habe gerade das `l` und das `O` aus der Liste der möglichen Zeichen entfernt. Damit sollte das Passwort eindeutiger zu lesen sein.

**Comment by dh3wr** [comment]
Super, vielleicht ein neues Master-Release?

**Comment by MarvinMenzerath** [comment]
Done
