### ISSUE TITLE
Make new release with default ID RIC changed form 1 to 8

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#166]
Wichtig wäre d7f2d4ce917dc36e378f465f349c9402b72a8330, die anderen Änderungen mit dem Colon könnten auch rein. Danke

**Comment by MarvinMenzerath** [comment]
Tag [v2.2.5](https://github.com/DecentralizedAmateurPagingNetwork/Web/releases/tag/v2.2.5) ist da.
