### ISSUE TITLE
Vertikale Platznutzung auf Homepage

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#170]
![grafik](https://user-images.githubusercontent.com/16710361/40978375-c4faf8a8-68d3-11e8-9bf7-611fc22687f4.png)

Oben und unten ist ja noch relativ viel Platz. Kann man das kompakter machen?

**Comment by MarvinMenzerath** [comment]
Kann man:

![image](https://user-images.githubusercontent.com/2064514/40979310-c251ed4e-68d5-11e8-8e55-549f4b85dabc.png)
