### ISSUE TITLE
Auto reload after Transmitter delete

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#171]
Passiert zu mindest bei eingetragenem Suchbegriff nicht

**Comment by MarvinMenzerath** [comment]
Das kann ich weiterhin nicht nachstellen. Auch bei einem eingetragenen Suchbegriff werden die Daten erneut vom Server geladen (siehe z.B. https://github.com/DecentralizedAmateurPagingNetwork/Web/blob/master/src/components/transmitter/Overview.vue#L267)

**Comment by dh3wr** [comment]
hmm jetzt geht es.. komisch
