### ISSUE TITLE
Reihenfolge bei News RSS Anzeige

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#172]
Laut https://hampager.de/dokuwiki/doku.php?id=blogoverview ist die Reihenfolge andersherum. Könnte man die Reihenfolge so machen, dass nach unten ältere Einträge angezeigt werden? Gibt es eine Limitierung der Anzahl der Einträge?

**Comment by MarvinMenzerath** [comment]
Ausschlaggebend für die Reihenfolge der Einträge ist der Zeitstempel der letzten Bearbeitung des Eintrags. Nur dieses Datum ist im Feed enthalten, daher kann nicht anders sortiert werden.

Eine Begrenzung auf die letzten 5 News-Einträge habe ich gerade eingefügt.
