### ISSUE TITLE
Font of RSS-News

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#175]
Wenn man genau hinschaut, ist das eine andere Schriftart:
![grafik](https://user-images.githubusercontent.com/16710361/41584850-ab31d84e-73a8-11e8-9ebc-9b1a812dd0b1.png)

Oder Farbe...

**Comment by MarvinMenzerath** [comment]
Laut Entwicklertools ist es die gleiche Schriftart, allerdings mit einer leicht unterschiedlichen Farbe...

**Comment by dh3wr** [comment]
Kann man das ändern/angleichen?
