### ISSUE TITLE
Start with Websocket-Implementation

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#177]
Background-Info:
https://www.rabbitmq.com/web-stomp.html
URL zum Testen: ws://dapnetdc1.db0sda.ampr.org:15674/ws (noch nicht aktiv, ich melde mich wenn)
Sollte auch per Datei einstellbar sein, wird sich auf jeden Fall noch ändern.

Welche Inhalte dann wo hin sollen, klärt sich heute Abend.

Was hiervon das Schönste ist, kann ich nicht beurteilen:
- https://www.npmjs.com/package/websocket
- https://www.npmjs.com/package/ws
- https://www.npmjs.com/package/websockets

**Comment by dh3wr** [comment]
URL geht, connect sollte also schon mal gehen

**Comment by dh3wr** [comment]
Es wird https://stomp.github.io/stomp-specification-1.2.html#STOMP_Frames über websockets gesprochen. Wie genau und was und warum wird noch definiert.

In diesem Sinne auch vielleicht interessant: https://www.npmjs.com/package/webstomp-client

**Comment by MarvinMenzerath** [comment]
Weiter geht es in #182
