### ISSUE TITLE
Eigenes Passwort ändern liefert 401

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#179]
Wenn man sein eigenes Passwort ändern möchte, bekommt man
````
{
  "code": 4010,
  "name": "Not Authorized",
  "message": "Invalid or missing username or password"
}
````
Der Core gibt im Log "Wrong Passwort" an. Die Auth. des REST PUT scheint nicht ok zu sein. Entweder es werden bereits die neuen Daten zur Auth. gesendet oder die alten, aber es werden die neuen erwartet letzteres Unwahrscheinlich.

**Comment by MarvinMenzerath** [comment]
Hier hat das Web-Frontend zuerst die lokalen Authentifizierungsdaten geändert und dann erst die Änderung zum Server geschickt, der die natürlich aufgrund des falschen Passworts nicht annehmen wollte.
