### ISSUE TITLE
Dateninkonsistenz beim Entfernen von Sendern in Sendergruppen

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#2]
Wenn man Sender entfernt oder hinzufügt und danach die Sendergruppen bearbeitet, sind die Sender-Vorschläge zum Auswählen nicht aktuell sondern auf dem alten Stand. Nach "Aktualisieren" geht's, aber es wäre schöner, wenn die Daten direkt aktuell wären.

**Comment by MarvinMenzerath** [comment]
Das von dir beschriebene Problem kann ich leider nicht nachvollziehen. Die Vorschläge beim Erstellen / Bearbeiten von Sendergruppen werden immer dann aktualisiert, wenn ein Sender erstellt / bearbeitet / gelöscht wird.
Allerdings habe ich gesehen, dass beim Löschen eines Senders, der in einer Sendergruppe enthalten ist, die Sendergruppen nicht neu geladen werden und dort in der Übersicht noch der gelöschte Sender angezeigt wird. Das habe ich in Commit 90182eb behoben.
