### ISSUE TITLE
Spalten in 1.2.1 nicht optimal

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#21]
Zeitpunkt könnte umgebrochen werden. Sendergruppen deutlich schmaler, Notfall könnte auch entweder ein Icon (rotes X wenn true, sonst nix) mit 32x32 Pixel werden und damit auch deutlich schmaler. So ist der eigentliche Text ja nicht besonders gut lesbar :)

![spalten](https://cloud.githubusercontent.com/assets/16710361/20067409/49da8fcc-a515-11e6-9087-3920672e44c8.PNG)

**Comment by MarvinMenzerath** [comment]
Das scheint ein Firefox-spezifisches Problem zu sein, da in Chrome die Spaltenbreite (wie es sein sollte) automatisch angepasst wird:
![](https://cloud.githubusercontent.com/assets/2064514/20131886/88186dbc-a660-11e6-8371-c49b387075cf.jpg)
