### ISSUE TITLE
Auto Update bei Sendern resettet immer die Tabelle

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#27]
Wenn man mal auf Seite 2 geklickt hat, kommt relativ schnell der reload und dann ist mal wieder auf Seite 1. Vielleicht entweder das Intervall deutlich verlängern oder
2. Den Tabellen-Stand beibehalten.

**Comment by MarvinMenzerath** [comment]
Momentan ist es so: die Daten der ausgewählen Seite werden (erneut) geladen, sobald sie (wieder) geöffnet wird. Außerdem werden alle 30s die Daten der gerade offenen Seite neugeladen.

Das Zwischenspeichern der geöffneten Seite der Tabelle und das anschließende Öffnen dieser Seite ist in meinen Augen "zu viel des Guten" und kann auch Probleme machen, wenn sich mehrere Einträge in der Zeit geändert haben oder komplett weggefallen sind.

Ich würde daher vorschlagen, das Auto-Update Intervall auf 60s oder mehr zu setzen oder eventuell sogar ganz zu entfernen...

**Comment by dh3wr** [comment]
dann entfernen :)

**Comment by dh3wr** [comment]
Könntest du das auch direkt bitte deployen auf db0sda.ampr.org. Wäre auch gut, eine neue Release zu machen damit. Aber warte noch, ich will noch auf der Startseite Infos zur Registrierung platzieren.

**Comment by MarvinMenzerath** [comment]
OK. Sag einfach Bescheid, wenn die Infos drin sind.
