### ISSUE TITLE
Lange Strings bei Länge und Breite geben Fehler "API nicht erreichbar"

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#28]
Wenn man bei den Sender-Daten recht lange Strings (nur Ziffern und .) eingibt, scheint wohl die API dies nicht zu mögen, die Fehlermeldung ist aber "API nicht erreichbar"  statt "String zu lang."

Könnte man entweder

1. Bereits bei der Eingabe die Werte auf 6 Nachkommastellen beschränken (und nochmal in der CORE-API nachschauen, was als valide validiert wird)
2. Oder die Werte vor der Übergabe an die API entsprechend runden?

**Comment by MarvinMenzerath** [comment]
Das Problem scheint auf Seiten des Cores zu liegen. Statt einer Fehlermeldung wird ein 500er geworfen, der im Web-Frontend die besagte Fehlermeldung provoziert.

Client-seitige Validierung würde ich immer auf ein (sinnvolles) Minimum beschränken, da sie sowieso umgangen werden kann...

Laut Core-Code sind die möglichen Eingaben wie folgt:
```java
@NotNull
@Digits(integer = 3, fraction = 8)
@Min(-180)
@Max(+180)
protected String longitude;

@NotNull
@Digits(integer = 3, fraction = 8)
@Min(-90)
@Max(+90)
protected String latitude;
```
