### ISSUE TITLE
Länge und Breite sind mit .   die Sendeleistung mit , als Dezimaltrennzeichen bei Sendern

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#29]
Gibt es dafür einen Grund?
Im übrigen können auch bei "Sendeleistung" die Hoch-Runter-Pfeile weg. Die wird niemand benutzen, sondern immer den Wert direkt eingeben.

**Comment by MarvinMenzerath** [comment]
Der Grund dafür ist, dass dieses Element ein `input`-Element vom Typ `number` ist und der Browser dabei standardmäßig die Darstellung an die Lokalisation des Benutzers anpasst und auch solche Kontrollflächen anzeigt.
Bei Längen-/Breitengrad habe ich das vor einiger Zeit auf eine "manuelle" Validierung umgestellt, da die Browser die Dezimaltrennzeichen unterschiedlich gehandhabt haben.
Hier kann ich das auch umstellen.
