### ISSUE TITLE
Upgrade to Admin -> Must set new Password

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#30]
Wenn ich einen Nutzer in den Admin-Status erheben möchte, muss ich ein neues Passwort vergeben. Das ist eher schlecht. Ist das ein Problem vom Web oder von der CORE-REST API?
![upgrade2admin](https://cloud.githubusercontent.com/assets/16710361/21142449/7be98c4a-c142-11e6-96aa-e63cf037c913.PNG)

**Comment by MarvinMenzerath** [comment]
Das scheint ein Problem vom Core zu sein. Änderungen werden hier nur dann akzeptiert, wenn alle Felder ausgefüllt wurden...

**Comment by dh3wr** [comment]
Kann man den Core entsprechend so um bauen, dass wenn ein Passwort schon da ist, das Fehlen des neu zu übermittelnden Passworts akzeptiert wird?

**Comment by MarvinMenzerath** [comment]
Das ist eine gute Frage, da hier wahrscheinlich wieder die Validierungslibrary eine Rolle spielt.
Genauso wie bei DecentralizedAmateurPagingNetwork/Core#40 muss ich mich erst in die Library einlesen und schauen, was sich damit machen lässt und was nicht (ohne weiteres) geht.
