### ISSUE TITLE
Empfängergruppen einrichten

### ISSUE THREAD

**Issue by phl0** [DecentralizedAmateurPagingNetwork/Web#32]
Mir kam gerade noch eine Idee: Die Möglichkeit, Empfänger zu einer Gruppe zusammen fassen zu können. Z.B. einen Ruf an die Gruppe N18 löst alle Empfänger der Mitglieder von N18 aus statt an jeden Pager einzeln einen Rufabsetzen zu müssen. So konnte man z.B. OV-News verteilen.

**Comment by dj7lc** [comment]
Das ist bereits möglich: Lege dazu das Clubstationsrufzeichen von N18 an (DL0CRE?) und trage dann zeilenweise die Pager-Nummern und Rufzeichen der OMs ein, die alarmiert werden sollen.

**Comment by phl0** [comment]
Ah danke für den Hinweis. Dann kann ich hier zumachen.

**Comment by phl0** [comment]
Hmm, doch noch eine Anmerkung. Vielleicht wäre es doch cooler, wenn man die Gruppe aus "Callsigns" zusammen bauen könnte. Das hätte den Vorteil, dass jeder seine Pagernummer selbst verwalten kann und "nur" Rufzeichen statt Nummern eingetragen werden müssen. Dann müsste man die Pagernummern nicht an zwei Stellen pflegen.

**Comment by MarvinMenzerath** [comment]
Das Issue, bzw. die Idee, wäre im Core wahrscheinlich besser aufgehoben...
