### ISSUE TITLE
Update for experimental branch Umkehrung des Verbindungsaufbaus

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#33]
Die neue Struktur sieht so aus. Ich kommentiere mal >>RW<< für ReadWrite und >>RO<< für ReadOnly. Bitte das Webinterface entsprechend anpassen.

"transmitters": [
    {
      "name": "test", >>RW<<
      "authKey": "test12345", >>RW<<
      "longitude": "11.324207", >>RW<<
      "latitude": "48.110602", >>RW<<
      "power": "15", >>RW<<
      "nodeName": "db0sda", >>RW<<
      "address": {
        "ip_addr": "44.225.164.228", >>RO<<
        "port": 43624 >>RO<<
      },
      "timeSlot": "2367ABEF", >>RW<<
      "ownerNames": [
        "admin" >>RW<<
      ],
      "deviceType": "SDRPager", >>RO<<
      "deviceVersion": "1.2-SCP-#2345678", >>RO<<
      "status": "OFFLINE" >>RO<<
    }
  ],

**Comment by dh3wr** [comment]
Kann mit Core auf 44.225.164.227 gefahrlos getestet werden.

**Comment by MarvinMenzerath** [comment]
Ist es gewollt, dass zum Erstellen und Abändern eines Transmitter-Objekts trotz `RO` immer noch `ip_addr`, `port` und `deviceType` angegeben werden müssen?

**Comment by dh3wr** [comment]
Nein das ist nicht gewollt. @Taronyu . Dies ist RO von Seiten des Webinterfaces

**Comment by MarvinMenzerath** [comment]
Beim Core von 44.225.164.227 tritt das Problem nicht mehr auf, beim "selbstgebauten" Core aus dem `experimental`-Branch jedoch schon.
Ich arbeite erstmal mit ersterem weiter...

**Comment by Taronyu** [comment]
Das müsste ja in der Transmitter.java geregelt sein. Und dort habe ich eigentlich die not null constraints für address und deviceType rausgenommen. Versteh ich jetzt nicht wirklich...

**Comment by Taronyu** [comment]
Hat sich das erledigt?

**Comment by MarvinMenzerath** [comment]
> Hat sich das erledigt?

Jap, das scheint ein Problem meines lokalen Builds gewesen zu sein. Ich muss mal schauen, was da schief gelaufen ist...
