### ISSUE TITLE
Länge und Breite automatisch aus Hamnetdb beziehen

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#34]
Hallo,
Es wäre schön, wenn man die Länge und Breite automatisch aus der hamnetdb beziehen könnte. Dazu Wäre folgenden notwendig:

- [ ] PHP Skript schreiben, welches http://hamnetdb.net/csv.cgi?tab=site herunterlädt
- [ ] Spalte "Callsign" vergleichen mit eingegebenem Callsign, dabei reicht es evtl. aus, wenn man das "Callsign" in der Tabelle als Substring findet, ebenfalls case-insensitive
- [ ] Ergebnisse zur Auswahl anzeigen und Möglichkeit zum automatischen übernehmen bereitstellen. Vielleicht mit Ajax? Ich stelle mir so eine Pop-Up-Lösung vor, die dann auf die original-Weboberfläche die Werte in die Felder schreibt.

Wäre das machbar?

**Comment by MarvinMenzerath** [comment]
Ich habe das folgendermaßen gelöst:
* das PHP-Skript liegt unter `http://db0sda.ampr.org/dapnet-update/callsignLocation.php`, bzw. `http://www.hampager.de/dapnet-update/callsignLocation.php` (dafür sollten wir uns einen besseren Ort aussuchen)
* wenn die Sender geladen werden, werden auch die Daten (Ajax-Request an das PHP-Skript) geladen
* eine Auswahlbox inkl. Suchfunktion neben dem Rufzeichennamen erlaubt die Auswahl eines Rufzeichens aus der Hamnetdb (s.u.)
    * bei der Bearbeitung eines Senders wird diese Option nicht aktiviert
* durch die Auswahl eines Rufzeichens aus der Liste werden Längen-/Breitengrad, sowie der Sendername gesetzt

![image](https://cloud.githubusercontent.com/assets/2064514/22883274/bc382148-f1ef-11e6-9edc-d6478367b50a.png)

![image](https://cloud.githubusercontent.com/assets/2064514/22883417/7a4725b2-f1f0-11e6-99df-3bb3442802cc.png)

**Comment by dh3wr** [comment]
Der Hammer, Marvin. Danke! Über den Ort müssen wir tatsächlich noch nachdenken.
