### ISSUE TITLE
Cross Ref. Eigenschaften von Sendern

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#35]
Muss dann natürlich hier auch verwurstet werden:
https://github.com/DecentralizedAmateurPagingNetwork/Core/issues/47

**Comment by dh3wr** [comment]
Hier ist der aktuelle Stand der REST API Erweiterung zur Umsetzung. https://github.com/DecentralizedAmateurPagingNetwork/Core/blob/experimental/src/main/java/org/dapnet/core/model/Transmitter.java
Bitte entsprechend einpflegen in die Weboberfläche.
Die Readonly oder ReadWrite Definition geht entweder aus der API hervor oder müsste diesem hier entsprechen:

    Höhe der Antenne über Grund in Metern [0 bis 1000] Einheit m, Type float
    Geplante Nutzung: Wide-Range-Sender oder privater Sender ["Widerange" | "Personal"]
    Art der Antenne (Omni oder Richtantenne) ["omni" | "directional"]
    Bei Richtantenne Hauptstrahlrichtung [0 bis 359] Typ float
    (Antennengewinn - Kabelverluste) in dBi [-50 bis + 80] Einheit dBi, Type float

**Comment by MarvinMenzerath** [comment]
Aktuell nimmt der Core aus dem `experimental`-Branch die Werte zwar entgegen, speichert sie aber nicht ab und gibt sie auch nicht wieder zurück.
Gibt es bereits eine Core-Version, die das macht und mit der ich testen kann *oder* eine grobe JSON-Struktur wie in https://github.com/DecentralizedAmateurPagingNetwork/Web/issues/33#issue-203976848?

**Comment by dh3wr** [comment]
Auf 44.225.164.227 läuft der experimental branch des cores. SSH Benutzer ist ihf, Passwort wie immer im IHF.

Hier die State.json aus dem Core für den Bereich

{
      "name": "c9000",
      "authKey": "c9000",
      "longitude": "11.324207",
      "latitude": "48.110602",
      "power": "15",
      "nodeName": "db0sda",
      "address": {
        "ip_addr": "44.225.167.249",
        "port": 51106
      },
      "timeSlot": "2367ABEF",
      "ownerNames": [
        "admin"
      ],
      "deviceType": "Dummy",
      "deviceVersion": "1.0",
      "status": "OFFLINE",
      "antennaAboveGroundLevel": 0,
      "antennaType": "OMNI",
      "antennaDirection": 0,
      "antennaGainDbi": 0.0,
      "usage": "PERSONAL"
    }

**Comment by MarvinMenzerath** [comment]
Alles klar, danke!
