### ISSUE TITLE
custom.js 404 und 8080 nur auf localhost aktiv

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#37]
In aktuellem Branch fehlt die Datei, wird aber angefordert

**Comment by dh3wr** [comment]
Auch kein Login möglich. Zum Testen: http://44.225.164.227/dapnet/

**Comment by MarvinMenzerath** [comment]
Das Fehlen der optionalen `custom.js` (siehe README unter Installation) ist unabhängig von der Erreichbarkeit des API-Servers.

Zum API-Server: Die Entwicklerkonsole sagt `Failed to load resource: net::ERR_CONNECTION_REFUSED http://44.225.164.227:8080/users/admin` und auch via `telnet` kann man den Server nicht erreichen.
Sicher, dass der Service läuft und der Port offen ist?

**Comment by dh3wr** [comment]
ihf@ihf-Satellite-Pro-S300L:~/DAPNET/Core/config$ telnet localhost 8080
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
*quit
^]
telnet> quit
Connection closed.
ihf@ihf-Satellite-Pro-S300L:~/DAPNET/Core/config$


Server scheint zu laufen. Víelleicht Firewall? 44.225.164.227, user ihf, Passwort wir auf den WindowsLaptops

**Comment by MarvinMenzerath** [comment]
Ich habe die Verbindung via `ssh -L 8080:localhost:8080 ihf@44.225.164.227` getunnelt und in der `config.json` die URL auf `localhost:8080` gesetzt.

Das Problem hier wird sein, dass der Port nach außen nicht offen ist oder dass der Server nur auf `127.0.0.1` bindet.

**Comment by dh3wr** [comment]
Es scheint, dass der Core sich nur an localhost bindet, nicht an alle Network Interfaces. Lokal auf 44.225.164.227:
ihf@ihf-Satellite-Pro-S300L:~/DAPNET/Core/config$ telnet 44.225.164.227 8080
Trying 44.225.164.227...
telnet: Unable to connect to remote host: Connection refused
ihf@ihf-Satellite-Pro-S300L:~/DAPNET/Core/config$

Das muss am Core liegen. Auf dem Rechner lokal telnet localhost 8080 geht.

**Comment by Taronyu** [comment]
Das Problem war folgende Zeile in der RestManager.java im Core: ` URI endpoint = new URI("http://localhost:" + Settings.getRestSettings().getPort() + "/");`

Der Endpoint wird also nur auf localhost verfügbar gemacht. Ich habe einen weitere Parameter in die Rest Settings eingebaut: Hostname. Der steht per Default auf "localhost", wenn man aber "0.0.0.0" einträgt, dann lauscht der Server auf allen Interfaces. Man kann auch den echten Hostnamen eintragen. Das gibt zum Teil aber Probleme, wenn der Host unter verschiedenen Adressen erreichbar ist.

**Comment by dh3wr** [comment]
Läuft. Vielen Dank euch beiden! via  5ae224a4e7ef149d29363c79d695aa598045f495

**Comment by dh3wr** [comment]
Closed via 5ae224
