### ISSUE TITLE
Button um Zufalls Auth Key zu generieren

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#38]
Die Liste in https://github.com/DecentralizedAmateurPagingNetwork/Core/issues/18 ist ja schon fast komplett abgearbeitet. Können wir noch einen Button in den Sendereigenschaften bekommen, der eine UUID (z.B.) 550e8400-e29b-11d4-a716-446655440000 generiert und in das Feld einträgt? Da die Sender anhand ihres Authkeys unterschieden werden, sollten wir hier wegen Dopplungen keine manuelle Eingabe von Werten wie "testkey" zulassen, sonden nur die automatisch generierte UUID.

**Comment by MarvinMenzerath** [comment]
Die generelle Generierung von einer UUID nach RFC4122 sollte kein Problem darstellen.

Allerdings würde ich eher den Weg gehen und den Core den Key generieren und damit vorgeben lassen. Dieser kann einfacher auf Dopplungen prüfen und lässt sich keine simplen manuellen Eingaben "unterschieben".
Eine Client-seitige Verifizierung kann man immer umgehen, im Web-Bereich sogar recht einfach.

**Comment by Taronyu** [comment]
Im aktuellen experimental Branch ist das jetzt drinnen. Mittels "/transmitters/auth_key" wird ein zufälliger Key erzeugt.

**Comment by MarvinMenzerath** [comment]
Wäre es nicht sinnvoller, wenn der Core beim Erstellen des Transmitters den Auth-Key selbst generiert und Read-Only ausgibt; dem User also keine Chance lässt ihn frei zu wählen?
Bei der aktuellen Lösung steht es dem REST-Client doch immer noch frei, den durch die API bezogenen Key zu akzeptieren oder einfach einen anderen zu wählen.

**Comment by Taronyu** [comment]
Ok, das hört sich in der Tat sinnvoller an. Leider haben wir kein getrenntes add/update und ich kann das in dem REST Handler auseinanderfrickeln. Top. Wo wir gerade bei Updates sind: Was passiert denn, wenn mir einfach jemand bei einem Update einen neuen Key mitschickt? Eigentlich ist die aktuelle Authkey-Lösung insgesamt eher bescheiden und man hätte doch ein username/password nehmen sollen (oder Transmittername + Passwort). Das Prüfen, ob der Key schon benutzt wird, ist momentan nämlich auch nicht threadsafe, da die Collection modifiziert werden kann und so einfach bekomme ich das auch nicht umgebaut, da es keine gemeinsamen Locks gibt.

**Comment by dh3wr** [comment]
Ist denn der Transmittername threadsafe eindeutig per se? Wenn ja, dann könnten wir das ja entsprechend umstellen. Ist vielleicht sogar von der Logik her einfacher, dass der Sender sagt, wer er ist statt nur einen Key zu schicken.

**Comment by Taronyu** [comment]
Da ist leider momentan überhaupt nichts threadsafe, das basiert auf normalen ArrayLists (gibt auch schon ein Issue im Core dazu). Gerade wenn wir das Protokoll noch überarbeiten, kann man leicht einen Namen + Key angeben.

**Comment by dj7lc** [comment]
Eine freie Wahl des Keys für jeden Sender wird dazu führen, dass "123456", "qwertz", usw. benutzt werden. Irgendwann loggen sich zwei verschiedene Sender mit demselben Key ein (was passiert dann?). Zur Vermeidung eines doppelten Keys könnten zum Beispiel Uhrzeit und Datum der Generierung plus Zufallszeichen benutzt werden.

**Comment by dh3wr** [comment]
@dj7lc: Statt nur Key würden wir ja den Sender-Namen als Identifier nehmen. Der ist ja eindeutig, wenn auch nicht threadsafe...

**Comment by Taronyu** [comment]
Ja, ich muss das eh mal umbauen an der Stelle glaube ich. Da wird ja auch noch einen sequentielle Suche gemacht, das ist auch nicht gerade die effizienteste Herangehensweise.

**Comment by Taronyu** [comment]
Ich habe das mal im Core umgebaut. Namen werden jetzt auch besser auf Eindeutigkeit geprüft, da das jetzt auf Maps basiert. Kann aber sein, dass sich da was an der Art der Serialisierung geändert hat und deswegen die State.json anders aussehen muss...

**Comment by Taronyu** [comment]
Ich habe die Authentifizierung im Core jetzt auf Transmittername und Passwort umgestellt.

**Comment by MarvinMenzerath** [comment]
Gab es dabei Änderungen an der API, die im Web-Interface umgesetzt werden müssten?

**Comment by Taronyu** [comment]
Das Passwortfeld kann jetzt im Prinzip einfach Freitext sein, die Generierung eines Keys habe ich wieder entfernt. Das war in der Form eh etwas umständlich implementiert.
