### ISSUE TITLE
Private Sender auf der Karte optional einblenden

### ISSUE THREAD

**Issue by dj7lc** [DecentralizedAmateurPagingNetwork/Web#41]
Wir haben eine große Zahl privater Testsender in Dapnet. Es wäre praktisch, diese z.B. über eine Checkbox "show widerange only" in den Statistiken und vor allem auf der Karte ausblenden zu können. Die manuelle Festlegung von Zeitschlitzen wird dadurch deutlich erleichtert.
Und ein zur Hälfte rotes Tortendiagramm bei den aktiven Sendern sieht irgendwie uncool aus ;-)

Damit könnte man noch etwas Kosmetik verbinden, indem Lokalsender auf der Karte kleinere Icons erhalten und im Hintergrund dargestellt werden.

**Comment by dh3wr** [comment]
Das fände ich auch gut. Mittlerweile sind 25 Sender wieder online, von denen die meisten widerange sind. Die Statistik erweckt aber den Eindruck, als ob das halbe Netz nicht da wäre. Daher würde ich das optinonale Ausblenden auch start befürworten. Oder noch besser: Optional die personal-Geräte einblenden.
