### ISSUE TITLE
Bei Passworten von Sendern nur [A-Za-z0-9] erlauben

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#43]
Es können auch z.B. Leerzeichen eingegeben werden, was Ärger macht. Bitte auf [A-Za-z0-9] beschränken und ggf. Hinweis ausgeben. Ich verweise da auch im Core drauf.

**Comment by MarvinMenzerath** [comment]
Sollen `-` und `_` erlaubt sein?

**Comment by MarvinMenzerath** [comment]
Der RegEx erlaubt jetzt folgende Zeichen: `[a-zA-Z0-9_-]`

**Comment by dh3wr** [comment]
Passwörter mit mehr als 1 Buchstaben Länge liefern nun 4060 Fehler. Ist das vom Core?

**Comment by dh3wr** [comment]
Bindestrich und Unterstrich würde ich aus rausnehmen. Gerade der Bindestrich kann Ärger machen.

**Comment by dh3wr** [comment]
Web scheint ok zu sein.
