### ISSUE TITLE
Sperrung der GUI-Elemente zur Bearbeitung von Ressourcen

### ISSUE THREAD

**Issue by Taronyu** [DecentralizedAmateurPagingNetwork/Web#46]
Ist hierfür noch was in der GUI zu tun? https://github.com/DecentralizedAmateurPagingNetwork/Core/issues/45

**Comment by MarvinMenzerath** [comment]
Für nicht-Admins (bzw. nicht-Besitzer) müssen die Elemente zum Anlegen / Bearbeiten / Entfernen angepasst werden
