### ISSUE TITLE
Rufzeichen und Sender auswählen

### ISSUE THREAD

**Issue by dk4pa** [DecentralizedAmateurPagingNetwork/Web#47]
Wenn man mobil einen Ruf absetzten möchte, kann ich das Rufzeichen und den Sender auswählen.
Die Rufzeichen und Sender können durch eine Scrollingfunktion ausgewählt werden.
Durch die importierten Nutzer ist es nun sehr schwer das gewünschte Rufzeichen zu finden.
Eine art Filterfunktion wäre hier super.

**Comment by MarvinMenzerath** [comment]
Im kommenden größeren Update wird das Problem mobil auf die gleiche Weise wie auf Desktop-Geräten mit einer Suchfunktion im Auswahlfeld gelöst:
![image](https://cloud.githubusercontent.com/assets/2064514/23860406/26a66b34-0807-11e7-8413-ee104f5a0bf6.png)

**Comment by dk4pa** [comment]
Moin, danke für die Info.
