### ISSUE TITLE
Bei empfangenen Rufen ist der Absender nicht klar -> automatisch einfügen

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#5]
Wenn ich einen Ruf empfange, weiß ich nicht von wem: Daher im Eingabe-Feld als Vorgabe <RUFZEICHEN>: am Anfang einblenden.

Beispiel:
DH3WR: Das ist ein sehr interessanter Ruf.

**Comment by MarvinMenzerath** [comment]
Soll das ganze dann ungefähr so aussehen (a83f8f1)?
![](https://cloud.githubusercontent.com/assets/2064514/19114231/5feb2b2c-8b0d-11e6-9872-303d78e2d0cd.jpg)

Nach dem Doppelpunkt folgt noch ein Leerzeichen und beim Öffnen des Containers setzt sich der Cursor automatisch an den Anfang des Eingabefeldes...

**Comment by dh3wr** [comment]
Vielleicht kann man den Cursor hinter dem Doppelpunkt platzieren? Als default.

**Comment by MarvinMenzerath** [comment]
Und Nutzernamen in Caps
