### ISSUE TITLE
Fehler nach Änderung des eigenen Passworts 

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#50]
Wenn man sein eigenes Passwort ändert, ist natürlich seine alte Auth nicht mehr gültig und man bekommt erst "ok" und dann "401" not authorized

Vielleicht kann man in der neuen Version nach einer Änderung des __eigenen__ Passworts automatisch einen logout machen?

**Comment by MarvinMenzerath** [comment]
Ist im nächsten großen Update gefixt!
