### ISSUE TITLE
Hilfe-Texte einfügen

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#56]
Sender:

Callsign:
Enter a valid amateur radio callsign of this transmitter. It will be also used for the 10 minute interval transmitter identification message to fulfill the law (at least the German law).

Search:
Easy import of stations from hamnetdb.net . Location data of the selected transmitter site will be copied into the form.

Node:
Select the DAPNET-Node which shall receive the transmitter TCP connection. Just this DAPNET-Node will accept connection for this specific transmitter.

Password:
Enter a authentication password for this transmitter. In the UniPager webinterface it’s called Auth Key.

Lat/Long:
Enter location of this transmitter in decimal form based on WGS84.

(3) Transmission Power -> Umbenennen in “Transmitter Power”
Feld kann auch deutlich kürzer werden. Sinnvolle Werte sind max. 3 stellig. Vielleicht kann man dann auch bei den anderen Feldern eine „Nebeneinander-Anordnung wählen, um die Seite nicht so lang zu machen? Die anderen Felder ebenfalls. Ich markiere mal die erwartete Stellenanzahl mit (x)

Enter the transmitter output power including your cable losses.

Usage:
For classification of the transmitters, there are two categories: Personal (Transmitters with low output power like RasPager) and Wide Range (Higher output power and elevated location site)

Antennatype: Umbenennen in Antenna Type
Please select if you have a omnidirectional antenna (e.g. X-50) or a directional antenna (e.g. Yagi)

(3) Antennadirection: Umbenennen in “Antenna main beam direction”
If this transmitter is connected to a directional antenna, please enter the antenna main beam direction in degrees according to “True North” (in German “rechtweisend Nord”)

(5) Antennalevel: Umbenennen in “Antenna elevation over ground”
Enter the antenna elevation over ground; NOT over NN (!) in meters.

(2) Antennagain: Umbenennen in “Antenna gain”
Enter the antenna gain in the main lobe direction for directional antennas and the average gain for omnidirectional antennas in dBi (dBi: Gain over isotropic radiator)

(8) Identification Address: Umbenennen in “Transmitter identification RIC”
Enter a RIC (default value is 1) which will be used to generate an artificial paging message containing the amateur radio callsign as given in this form.

Ower:
If you are an owner, you can change the parameters for this transmitter.

Calls:

Message:
Das Absender-Call bitte in Großbuchstaben in der Vorlage
Enter your paging text. Your callsign is added automatically.

Callsigns:
Select on or multiple callsigns you what to send the message to.

Transmittergroups: Umbenennen in Transmitter Groups:
Select a logical transmitter group that should broadcast you message. Default is all transmitters, but if you know the approximate location of the receiver you might limit the transmitters used for your paging to a certain area. This reduced the load on the transmitters.
Noch was: Kannst du all als default Value schon voreintragen?

Emergency?
In case you want your message to be delivered as soon as possible, check this box. No harmful things will happen, the DAPNET will just process your message with maximum priority. Please make a fair use of this feature.

Callsigns:
Callsign:
Please enter a valid amateur radio callsign of a human or a classifying name of a organization.

Description:
Provide your name or any other useful description of this entry.

Pager:
1 Add one or more lines of pager RIC numbers
2 Add a corresponding number for lines as a description for the RIC numbers given in the first box.

Owner:
An owner of a callsign association can edit the parameters of this callsign.

**Comment by MarvinMenzerath** [comment]
c514b4f299785277b4088f2ac366966ede644738

**Comment by dh3wr** [comment]
Callsigns:
Bitte das Beispiel Bild direkt anzeigen unter dem Hilfetext der Box.
Ebenfalls dort Ändern:
Alt: Please enter a valid amateur radio callsign of a human or a classifying name of a organization.
Neu: Please enter a valid amateur radio callsign of a human or a classifying name of __an__ organization.

Transmitter:
Alt: Just this DAPNET-Node will accept connection for this specific transmitter.
Neu: Just this DAPNET-Node will accept a connection from this specific transmitter.

Bei den anderen Texten Großschreibung nach Doppelpunkt.
Alt <*>: enter
Neu <*>: Enter

Neuer Text für die Timeslots:
As all transmitters use the same frequency a time division multiplex access scheme is used. There are 16 timeslots available. Assign the slots of this transmitter according to you surrounding transmitters in your neighborhood without overlapping timeslots that are assigned to more than one transmitter. You can use the transmitter map to check already assigned timeslots of adjacent transmitters. In case that you cannot fulfill your requirements, contact the adjacent transmitter owners and try to get an aggreement. Normally four 4 or less timeslots per transmitter are more than enough.

**Comment by dh3wr** [comment]
Rubric Text:
Rubrics are a Skyper based invention allowing to send news sorted into chategories (the rubrics). Assign the number with care and contact rwth-afu@online.de in case of doubt. Be aware that the number of rubrics is limited netwide to 99.

Rubrics Edit:
Alt Transmittergroups
Neu Transmitter Groups
(Das kannst du auch bei allen *groups mal überprüfen.

**Comment by dh3wr** [comment]
New Calls:
Alt: Select a logical transmitter group that should broadcast you message.
Neu: Select a logical transmitter group that should broadcast your message.
