### ISSUE TITLE
Sprachen-Unterstützung

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#57]
Es soll die Browser-Sprache erkannt werden und entsprechend eine Übersetzung der Texte angezeigt werden.

**Comment by dh3wr** [comment]
Es gibt doch einige User, die des Englischen nur mäßig mächtig sind. Das Ticket ist ja schon etwas älter, ich würde gerne die Bearbeitung nochmal anstoßen wollen. Danke!

**Comment by MarvinMenzerath** [comment]
Ich habe die entsprechende Bibliothek und ein paar Beispielübersetzungen eingepflegt.

Grundsätzlich funktioniert das Ganze so:
* Standardsprache ist Englisch, der Nutzer kann im Footer die Auswahl ändern. Die ausgewählte Sprache wird im Browser dauerhaft gespeichert.
* Die Übersetzungen liegen im Verzeichnis `src/i18n/` (z.B. als `de.json`) und sind als JSON-Struktur aufgebaut.
* Die dort angegebenen Strings werden im Template (z.B. in `src/components/Home.vue`) durch ein `{{ $t('path.to.translation') }}` referenziert.
* Enthält der übersetzte String HTML, muss folgende Syntax verwendet werden: `<p v-html="$t('path.to.translation')"></p>`.
* Platzhalter in der Übersetzung werden durch ein `{ replaceme }` definiert und müssen mit `{{ $t('path.to.translation', { replaceme: 'replaced' }) }}` angesprochen werden.
* Um einen String im JavaScript Code zu referenzieren, muss `this.$i18n.t('path.to.translation');` verwendet werden.
* Vollständige Dokumentation: https://kazupon.github.io/vue-i18n/en/

**Comment by dh3wr** [comment]
''Yes'' und ''No'' der Tabelle können nicht mit ccd64325647ecc5a64d8bee506cafe58c7ddb3db ersetzt werden

**Comment by MarvinMenzerath** [comment]
Framework ist vorhanden und alle Strings in den entsprechenden i18n-Dateien eingetragen.
Ich mache das hier als "Sammelissue" einmal zu, und bei Problemen am besten ein eigenes Issue aufmachen.
