### ISSUE TITLE
Bei nicht verbundenen Knoten fehlt die IP, aber die HTML-Tabelle kommt drauf nicht klar

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#6]
Wenn ein Knoten nicht verbunden ist, kann die IP-Adresse nicht abgerufen werden. Das ärgert aber wohl die Tabelle.

![bug2](https://cloud.githubusercontent.com/assets/16710361/19154485/f87053fe-8bda-11e6-91b7-e046acfd1eea.PNG)

**Comment by MarvinMenzerath** [comment]
Der Umstand sollte in der Dokumentation der API im Core-Wiki vermerkt werden...
