### ISSUE TITLE
Nutzer anlegen mit eigenem Passwort klappt nicht

### ISSUE THREAD

**Issue by phl0** [DecentralizedAmateurPagingNetwork/Web#60]
Ein User kann nicht angelegt werden, wenn man das Passwort selbst generiert und einträgt. Das gilt auch für die Passwort ändern Funktion. 

![screenshot from 2017-05-02 10-20-57](https://cloud.githubusercontent.com/assets/7112907/25609795/0feafd06-2f21-11e7-84a6-fe9903599fab.png)

**Comment by dh3wr** [comment]
Kann ich bestätigen
