### ISSUE TITLE
DAPNET-Import

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#61]
http://www.hampager.de/dapnet-import geht nicht. Warum? Ist das im Web-Repo drin? Wie war das nochmal?

**Comment by MarvinMenzerath** [comment]
Die Seite lag im Web-Root-Verzeichnis des öffentlichen DAPNET Web.
Mit der Umstellung auf die neue Version ist das wohl verloren gegangen.

Sinnvollerweise sollten wir die Import-Seite in einem eigenen Verzeichnis unter `/srv` ablegen und dann durch die Apache-Konfiguration dorthin verweisen.

**Comment by MarvinMenzerath** [comment]
Habe die Seite in das Verzeichnis `/srv/dapnet-import/website` geladen, die Datenbank eingespielt und die Zugangsdaten eingerichtet.
Die Konfiguration befindet sich in der `/etc/apache2/sites-enabled/www.hampager.de.conf`-Datei.
