### ISSUE TITLE
"Statistics"-Tortendiagramm des Sendertyps

### ISSUE THREAD

**Issue by MurrayBozinsky** [DecentralizedAmateurPagingNetwork/Web#62]
Der Sendertyp "Unknown" wird als der häufigste oder
zweithäufigste Sendertyp im Tortendiagramm auf der Seite
"All Transmitters" dargestellt.
Ich habe mal eben die Liste durchgezählt - die meisten
Sender unbekannten Sendertyps sind nicht online - entweder
waren sie noch nie oder sind schon länger ausser Betrieb.

Wäre es daher sinnvoll die nicht "Online" stehenden Sender aus dem
Sendertyp-Tortendiagramm rauszunehmen ?

**Comment by MarvinMenzerath** [comment]
Klingt für mich auch nach einer sinnvollen Änderung
