### ISSUE TITLE
Nodes auf Karte anzeigen

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#64]
Könnte man optional die Nodes auf der Karte anzeigen? Ein entsprechendes Icon müssen wir noch finden mit online/offline-Darstellung. Ebenfalls wären Linien von den Sendern zu den entsprechenden Nodes schön, die dann auch angezeigt werden, wenn man die Nodes einblendet. Ich suche noch die Icons

**Comment by MarvinMenzerath** [comment]
Habe das Feature mit einem einfachen Icon implementiert. Wenn du ein geeignetes Icon findest, kann ich das austauschen...

**Comment by dh3wr** [comment]
Die Farben bitte auf dunkle Farben begrenzen. Evtl. durch Transformation nach HSV und dann Beschränkung des Farb-Werte und Rücktransformation.
![grafik](https://cloud.githubusercontent.com/assets/16710361/25796844/641fc65e-33db-11e7-8ff3-1aca94352e5d.png)

**Comment by dh3wr** [comment]
Das Symbol ist eigentlich ok so. Kann man das noch abhänig vom Status (online, suspended, unkown) einfärben?

**Comment by dh3wr** [comment]
Und in der Info-Box IP und Port sowie eine Liste der zugeordneten Sender angeben,  wenn das nicht zu schwer ist,.
