### ISSUE TITLE
Email an Node-Owner

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#65]
Siehe https://github.com/DecentralizedAmateurPagingNetwork/Core/issues/90
Kann man schon mal vorbereiten, die Owner-Eigenschaft in der Tabelle anzuzeigen. Wird wohl bald implementiert.
Ebenfalls wäre unter "Actions" für admins ein HTML-Link mit ``mailto:`` schön, der eine Email an alle Node-Owner schickt.

**Comment by dh3wr** [comment]
"nodes": {
  "node_name": {
    "name": "node1",
    "ownerNames": [ "node_owner" ],
    ...
  }
}

Ist schon commited, aber noch nicht auf den Produktionsservern. Kann aber schon mal vorbereitet werden.

**Comment by MarvinMenzerath** [comment]
Erledigt
