### ISSUE TITLE
Update Node liefert 0 bei Lat. und Long.

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#68]
Auch wenn Werte eingetragen wurden.
![grafik](https://cloud.githubusercontent.com/assets/16710361/25843422/9d6977da-34a7-11e7-94c5-a270e150cd24.png)

Es liegt daran, wenn die Zahlen mit Punkt statt Komma getrennt sind. Ist Punkt vorhanden, so wird 0 gePUTet. Aber keine Fehlermeldung. Vielleicht einfach beide Varianten abfangen?

**Comment by MarvinMenzerath** [comment]
Hier scheint es einen Unterschied zwischen Chrome und Firefox zu geben:
während Chrome in diesen Feldern wie gewünscht nur Ziffern und Punkte (zumindest bei englischer Spracheinstellung; wobei angezeigte Kommata als Punkte abgesendet werden iirc) als Eingaben zulässt, lässt Firefox erstmal alle Zeichen zu. Hier muss man wohl manuell die Eingaben filtern...
