### ISSUE TITLE
DAPNET Update

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#76]
![grafik](https://cloud.githubusercontent.com/assets/16710361/25996859/9e79d33a-3719-11e7-88ad-402a5d532810.png)

**Comment by MarvinMenzerath** [comment]
Da steht absichtlich noch die alte Version, bis v2.0.0 "fertig" ist.

**Comment by dh3wr** [comment]
ok

**Comment by MarvinMenzerath** [comment]
Wäre dann [hiermit](https://github.com/DecentralizedAmateurPagingNetwork/Web/releases/tag/v2.0.0) erledigt.
