### ISSUE TITLE
Menschen lesen Hilfe-Text zum import nicht

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#77]
Schon der 2., der mich nach dem Passwort nach dem Import fragt. :-/

Daher bitte den Hinweis-Text entsprechend erweitern:
To log use your callsign for _both_ **username** and **password**.

Vielleicht hilft das.

**Comment by MarvinMenzerath** [comment]
https://github.com/DecentralizedAmateurPagingNetwork/Import/commit/effccfdf9c34fba23edaa1bb9a7ea13c98280c7f
