### ISSUE TITLE
Sender zu Knoten-Zugehörigkeit wird wegfallen

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#79]
Siehe https://github.com/DecentralizedAmateurPagingNetwork/Core/issues/101  Wenn das geschlossen ist, auch das Webinterface anpassen und bei den Sendereigenschaften die Node-Zugehörigkeit wegfallen lassen.

**Comment by dh3wr** [comment]
Aber als speichern, wo der Sender gerade eingewählt ist, könnten wir schon noch. Zur Info und auch für die Liniendarstellung auf dem Webinterface. Das wird dann quasi Read only.

**Comment by MarvinMenzerath** [comment]
Also im Formular zur Erstellung/Bearbeitung das Node-Feld entfernen, ansonsten aber in der Übersicht und auf der Karte weiterhin anzeigen.
Das `nodeName`-Attribut bleibt in der Sender-API (read-only) bestehen?
