### ISSUE TITLE
Optionale Anzeige der Zeitschlitze als kleiner Text unter den Sender-Icons

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#81]
Wenn man sich einen freien Zeitschlitz für einen neuen Sender sucht, muss man alle Sprechblasen aufklicken und sich dann merken, welche dort aufgeführt sind.
Könnte man per check-box unter der Karte eine Option einbauen, die die Zeitschlitze als kleinen Text unter das Sender-Symbol einblendet? Dann hat man in der Umgebung des neuen Sender-Standorts direkt die Übersicht.

**Comment by MarvinMenzerath** [comment]
Leaflet bietet keine Option, um unterhalb der Marker noch Text o.Ä. anzuzeigen.
Die einzige Möglichkeit wären Tooltips, die sich allerdings auch erst dann öffnen, wenn man mit der Maus über den Marker fährt.

**Comment by dh3wr** [comment]
Was ist hiermit? http://leafletjs.com/reference-1.0.0.html#tooltip wird das schon verwendet?

**Comment by MarvinMenzerath** [comment]
Das Tooltip ist nichts anderes als ein Marker-Popup, das beim MouseOver angezeigt wird:
![image](https://cloud.githubusercontent.com/assets/2064514/26540061/d4404f1a-444f-11e7-898a-cdfc7953052e.png)

**Comment by dh3wr** [comment]
Ok, dann vergessen wir das.
