### ISSUE TITLE
Verpflichtende Email-Adressen Angabe beim User-Import

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#82]
Wir haben jetzt ca 30 Leute mit imported@user.com als Email. Bitte um Formular direkt die Email abfragen und mit Regex validieren. Und dann den User entsprechend anlegen.
Was ist eigentlich, wenn es den User schon gibt? Dann sollten wir den Import auf jeden Fall verweigern, um nichts zu überschreiben.

**Comment by MarvinMenzerath** [comment]
https://github.com/DecentralizedAmateurPagingNetwork/Import/commit/d7666b1b71e303f4eee2bdc3bec0513e08d6c713
