### ISSUE TITLE
Node auf Suspended setzen geht nicht

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#86]
Kann es sein, dass die PUT Anfrage nicht richtig ist? Ich habe suspended ausgewählt.

``12:10:02.592 [Incoming-1,DAPNET1.1.3.8-SNAPSHOT,db0ffl] INFO  org.dapnet.core.cluster.RpcListener - PutNode Node{status=UNKNOWN, name='db0fa'}: OK`

**Comment by MarvinMenzerath** [comment]
Laut Netzwerkprotokoll vom Chrome-Browser wird genau der Status gesendet, der auch ausgewählt wurde.
Interessanterweise kommt dann in der Response nicht unbedingt der gewählte Status zurück. Wäre aus meiner Sicht ein Problem vom Core...

**Comment by dh3wr** [comment]
Hat sich erledigt
