### ISSUE TITLE
Nachrichten öffentlich

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#9]
Die Nachrichten auf der Startseite könnten auch öffentlich zu lesen sein. Wo kommen die eigentlich her?

**Comment by dh3wr** [comment]
Die Nachrichten auf der Startseite könnten auch öffentlich zu lesen sein. Wo kommen die eigentlich her?

**Comment by MarvinMenzerath** [comment]
Alle möglichen Nachrichten anzeigen statt nur welche aus festgelegter Rubrik.

**Comment by MarvinMenzerath** [comment]
Ganz raus.
