### ISSUE TITLE
Darstellungsproblem

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#90]
DC7IA schreibt:
Hallo,

ich habe DAPNET Core und Web installiert um mir das mal anzuschauen. Beim Aufruf von Dapnet Web bekomme ich folgende Meldung in der Firefox Web-Konsole:

> Error: Module build failed: SyntaxError: Unexpected number in JSON at position 248
>     at JSON.parse (<anonymous>)
>     at Object.module.exports (/opt/dapnet/Web/node_modules/json-loader/index.js:7:48)

Ich habe keine Idee, was das bedeuten sollte. Vielleicht kann mir zufällig jemand helfen? Ich spreche leider kein Javascript.

Ich habe schon probiert es mal neu zu kompilieren, jedoch ohnne Erfolg.

vy 73 Joshua DC7IA

**Comment by MarvinMenzerath** [comment]
Insofern die Installationsanweisungen in der README-Datei befolgt wurden, kann so ein Fehler gar nicht in der Firefox Web-Konsole auftreten...
