### ISSUE TITLE
Preloading of images 

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#94]
Ich bin gerade in edge Land und z.b. das drehende Bild mit den Pfeilen wird erst recht spät geladen.

**Comment by MarvinMenzerath** [comment]
Wie stellst du dir das vor?

Der sich drehende Pfeil gehört zu Font Awesome und wird als Schriftart eingebunden.
Normalerweise sollte dein Browser die assets (also Schriften, Bilder, etc.) cachen, außer der Webserver schickt entsprechende Header mit...

**Comment by dh3wr** [comment]
ok, dann war es wohl das späte rendering im mobilen Firefox. Ich dachte, die Pfeile wären ein Bild, was erst nach beim Aktualisieren der Tabellen geladen wird. Sonst könnte man das schon mal mit CSS vorladen beim Seitenaufruf, damit es im Cache ist.
