### ISSUE TITLE
Kartenansicht nach Zeitschlitz

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#95]
Wie besprochen unter der Karte eine Checkbox "Show transmitters by timeslots", daneben ein nur bei ausgewählter Checkbox aktives Zahleneingabefeld mit Hoch-Runter-Pfeilen. Wertebereich 0 bis F. Dann in der Karte nur die Sender mit dem ausgewähltem Zeitschlitz anzeigen. Die Wide-Range-Only oder auch nicht-Funktionalität soll weiterhin funktionieren.

**Comment by MarvinMenzerath** [comment]
Habe statt der Eingabe eines einzelnen Zeichens die Eingabe einer Zeichenkette erlaubt.
Bei einem Wertebereich außerhalb von 0 - 9 ist außerdem die Verwendung der Hoch-/Runter-Pfeile nicht möglich.

**Comment by dh3wr** [comment]
Man muss den Zeitschlitz in Großbuchstaben eingeben, wenn er zwischen A und F ist. Bitte ein uppercase(eingabetext) davonsetzen.

**Comment by dh3wr** [comment]
Ein eine kurze Beschreibung, was das Eingabefeld soll.

**Comment by MarvinMenzerath** [comment]
https://github.com/DecentralizedAmateurPagingNetwork/Web/commit/7945236a21bb354271f06f2b543b23b1a0bdc5df
