### ISSUE TITLE
Compressed content transfer und apache.conf

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#97]
Bitte man nachschauen, wie man den Apache konfigurieren muss, damit zumindest der JS-Kram gezipt übertragen wird.

Vielleicht kann man auch eine apache.conf beim npm build erstellen, die diese Konfig enthält und außerdem das /dist Verzeichnis direkt einbaut? Dieses könnte man dann in conf-enabled mittels symlink einbinden. Ähnlich zu Paketen wie munin, die auch ihre eigene .conf für Apache mitbringen.

**Comment by Taronyu** [comment]
Also zumindest in meinem Firefox wird schon `Content-Encoding: "gzip"` ausgeliefert. Besser wird das an der Stelle mit Bordmitteln auch nicht mehr.

**Comment by MarvinMenzerath** [comment]
[Diese Seite](http://codebeerstartups.com/2012/10/how-to-set-an-expires-header-in-apache/) hat eine kurze, aber gute Anleitung wie man die Expires-Header konfigurieren und GZIP aktivieren kann.

**Comment by MarvinMenzerath** [comment]
Gibt es hier Neuigkeiten?

**Comment by dh3wr** [comment]
@MarvinMenzerath Könntest du dich bitte um die Umsetzung auf dapnet.db0sda.ampr.org dieser gzip-Geschichte kümmern und bei Erfolg das in die Readme reinschreiben?

**Comment by MarvinMenzerath** [comment]
Habe die Änderungen durchgeführt und eine Anleitung im Repo-eigenen Wiki (https://github.com/DecentralizedAmateurPagingNetwork/Web/wiki/Apache-2:-Caching-&-gzip) hinterlegt.
