### ISSUE TITLE
Auf der Import-Seite kommt man nicht zurück auf die Hauptseite

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#98]
Hier http://www.hampager.de/dapnet-import/ liefert ein Klick auf das DAPNET-Logo die gleiche Seite. Wahrscheinlich ist der Link relativ auf . und nicht auf ../

**Comment by MarvinMenzerath** [comment]
https://github.com/DecentralizedAmateurPagingNetwork/Import/commit/35b20cd2df4ed52c62691cc70c1a871d0945398a
