### ISSUE TITLE
DAPNET-Import: Text wird nicht gelesen

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#99]
Ich bekommen zunehmend Anfragen, was denn das Passwort nach dem Import sei. Wir müssen den Information-Text mehr ins Auge springend machen. Entweder rot und dicker oder ein Popup oder Ähnliches, bei dem man auf "habe ich gelesen" klicken muss. Am besten noch mit einer Frage, bei der man nachdenken muss. Z.B.
``Which wavelength corresponds to 435 MHz?`` Mit einem Drop-Down-Auswahlmenu und möglichen Antworten

- 80 m
- 70 cm
- 5.6 m

Antwort 2 ist richtig, nun dann wird der Import gemacht. Antwort 1 ist die default-Antwort. Vielleicht machen wir das auch alles in dem Formular:
Eingabefelder
Hinweis in rot und dick
Checkbox: I have read and understood the information and know my login name und password.
Frage

**Comment by MarvinMenzerath** [comment]
Habe erst einmal nur die Checkbox eingebaut:
![image](https://user-images.githubusercontent.com/2064514/27470603-00fab7bc-57f5-11e7-9bc5-5a257354a2ed.png)

**Comment by dh3wr** [comment]
Da lassen wir das mal so und machen es zur Not nochmal auf.
